### ISSUE TITLE
Sticky events producer in the Job

### ISSUE THREAD

**Issue by yigit** [yigit/android-priority-jobqueue#1]
_From @mecid on March 1, 2015 15:58_

I have Job which produce sticky event as a result of the Job. But i need to register Job to provide sticky events. Which lifecycle methods of the Job i need to use for register/unregister ? I am using Otto event bus.

_Copied from original issue: path/android-priority-jobqueue#97_

**Comment by yigit** [comment]
Are you trying to listen for events from your job? That seems unexpected.
Or do you need to register just to dispatch events?
I never used otto so I don't know but needing to register to dispatch events seems weird too.

Unfortunately, there is no "done" callback in jobs :/. We can consider adding one but can you add more details on why this is needed?

**Comment by mecid** [comment]
@yigit 

I have a fragment which register to event and i have a job which post this event. 
I need to get this event after fragment configuration change.

**Comment by yigit** [comment]
if your job is only posting events, why does it need to register?

**Comment by mecid** [comment]
@yigit sticky event producers must also be registered, like subscribers.
http://square.github.io/otto/

**Comment by yigit** [comment]
ugh :/. ok, since we don't have a callback when a job is done what you can do is implement your unregister call at the end of `run` and `onCancel`. 
If you can send a pull request for calling an onFinished method, I'm happy to accept it.
BaseJob should call it inside a try catch block if onRun succeeds or onCancel is called.

Somewhere around these lines: https://github.com/yigit/android-priority-jobqueue/blob/master/jobqueue/src/com/path/android/jobqueue/BaseJob.java#L107

**Comment by mecid** [comment]
@yigit after unregister otto removes last posted event from memory. Any idea how can i handle this behaviour?

**Comment by yigit** [comment]
honestly, i don't think job should be the dispatcher if your event has to be sticky because jobs are temporary things. Maybe you should call some long living controller from the Job and dispatches the event?

**Comment by mecid** [comment]
@yigit agree. Please close the issue.
