### ISSUE TITLE
Throw Exception from withing a callback listener

### ISSUE THREAD

**Issue by vanheerdena** [yigit/android-priority-jobqueue#100]
Hi,

I'm sure there is a simple solution but I am struggling to figure out how to get onRun() to throw and error once my firebase server responds with an onComplete() event. 

```
@Override public void onRun() throws Throwable {
GeoFire geoFire = new GeoFire(new Firebase("key");
    geoFire.setLocation(this.geoID,
        new GeoLocation(ll.latitude, ll.longitude),new GeoFire.CompletionListener() {
          @Override public void onComplete(String key, FirebaseError error) {
            if (error != null) {
              System.err.println("There was an error saving the location to GeoFire: " + error);
              throw new Exception("Unexpected error posting to Firebase");
            } else {
              System.out.println("Location saved on server successfully!");
            }
          }
        }
    ) ;
  }
```

The issue is on the throw new exception line with the error being I have an unhandled exception. Any ideas how to handle this situation? 

Thank so much for your time with this silly issue.
Al

**Comment by yigit** [comment]
@Override public void onRun() throws Throwable {
        final Throwable[] throwable = new Throwable[1];
        final CountDownLatch ready = new CountDownLatch(1);
        GeoFire geoFire = new GeoFire(new Firebase("key");
            geoFire.setLocation(this.geoID,
                new GeoLocation(ll.latitude, ll.longitude),new GeoFire.CompletionListener() {
                  @Override public void onComplete(String key, FirebaseError error) {
                    if (error != null) {
                      System.err.println("There was an error saving the location to GeoFire: " + error);
                      throwable[0] = new Exception("Unexpected error posting to Firebase");
                    } else {
                      System.out.println("Location saved on server successfully!");
                    }
                    ready.countdown();
                  }
                }
            ) ;
          }
          ready.await(<some query timeout you want>);
          if (throwable[0] != null) throw throwable[0];

though seems like firebase API is already async so triggering it in a job does not make much sense. You should be  using a sync firebase API (if it exists)

**Comment by vanheerdena** [comment]
Thank you so much for the quick help and suggestion.
