### ISSUE TITLE
v2 branch: Callbacks triggered multiple times

### ISSUE THREAD

**Issue by 3flex** [yigit/android-priority-jobqueue#102]
Not sure what's causing this:

* Add job 1 and let it complete
* Callbacks are triggered 1 time
* Add job 2 and let it complete
* Callbacks are triggered 2 times
* Add job 3 and let it complete
* Callbacks are triggered 3 times

I'd expect each job to only trigger the applicable callbacks once:

* Add job 1 and let it complete
* Callbacks will be triggered 1 time
* Add job 2 and let it complete
* Callbacks will be triggered 1 time
* Add job 3 and let it complete
* Callbacks will be triggered 1 time

**Comment by yigit** [comment]
Can you share how you are attaching callbacks? Are you sure you are not attaching multiple callbacks? Also, when a callback is called, can you log the job ids?

**Comment by 3flex** [comment]
I cannot replicate now.

When adding a job I start a service to run the JobManager, and in the service's `onCreate` I add the callbacks. In service's `onDestroy` I remove the callback.
