### ISSUE TITLE
onRun not working

### ISSUE THREAD

**Issue by georgethms10** [yigit/android-priority-jobqueue#103]
http://stackoverflow.com/questions/35570010/onrun-of-android-priority-jobqueue-not-called

**Comment by yigit** [comment]
can you please submit an app that reproduces your issue? Or at least enable logs and publish logs.

**Comment by eliasbagley** [comment]
I'm having the same issue, and for me it happens only if I add `persist()` to my `Params`. Someone in the comments on that stackoverflow post mentioned that he thinks it's a problem with serialization. @yigit would it be possible to detect this and throw an exception or somehow notify when a job is unable to be serialized/persisted?

**Comment by eliasbagley** [comment]
Ah! Found what was causing this for me - I am storing a POJO in an instance variable in my Job subclass, and `onRun()` was never getting called. It started getting called once I made my POJO implement `Serializable`. I know I remember reading somewhere in the docs that JobManager persists jobs using Java serialization by default, but I think it would be beneficial to others to either 1) bring more attention to the fact that persisted objects need to implement `Serializable`, or 2) somehow check for this and throw an exception if they are trying to persist a Job which has non-serializable member variables.

**Comment by yigit** [comment]
i think it was a very bad API decision to hide serializing errors.
I think it is still better to keep surpres deserialization errors but I'll make JobManager crash if it fails while serializing a job. Thanks for the feedback.

**Comment by pointblankcoder** [comment]
This exact situation happened to me and as @eliasbagley mentioned it was due to a non-serializable object being stored as an instance variable in my `Job`.
Fortunately I didn't need to store this variable on instantiation as it was a simple SQL query attached to my ORM.
Must admit it was confusing at first, I was unable to find any logs related to a deserialization error unless I had it filtered somehow, which is possible. Anyway thank you for the solution!
@yigit great lib by the way, keep up the good work. Making my development a lot easier.

**Comment by JimVanG** [comment]
I'd like to add to the conversation that configuring the [CustomLogger](https://github.com/yigit/android-priority-jobqueue/blob/master/examples/twitter/TwitterClient/src/com/birbit/android/jobqueue/examples/twitter/TwitterApplication.java#L36-L57) helps a lot with debugging. It'll pin-point any Serialization errors that you have, saving A LOT of time! (Wish I knew to set the CustomLogger from the beginning...)

**Comment by yigit** [comment]
I've changed job manager to have an error logger by default.
I'm also planning to change it to crash when the serializer throws an exception.

**Comment by digiperfect-bharat** [comment]
protected RetryConstraint shouldReRunOnThrowable(Throwable throwable, int runCount, int maxRunCount) {
        return RetryConstraint.createExponentialBackoff(20, 2000L);
    }

not retrying if failed due to server connectivity exception
