### ISSUE TITLE
V2. cannot be found 

### ISSUE THREAD

**Issue by ninjahoahong** [yigit/android-priority-jobqueue#105]
I have follow the instruction and add the dependency to my gradle as follow:
```
buildscript {
    repositories {
        jcenter()
        mavenCentral()
        maven {
            // This is for priority queue
            url 'https://oss.sonatype.org/content/repositories/snapshots/'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.0.0-beta6'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}
```

and 

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    .....

    // Priority queue for better handling tasks, determine which ones to be run first
    compile 'com.birbit:android-priority-jobqueue:2.0.0-SNAPSHOT@aar'
}
```
But the dependency could not be found. What is missing in my code in order for the code to work. Thank you so much.

> 
> Error:Could not find com.birbit:android-priority-jobqueue:2.0.0-SNAPSHOT.
> Required by:
>     g2a-deal:app:unspecified
> <a href="searchInBuildFiles">Search in build.gradle files</a>

**Comment by yigit** [comment]
hi sorry, i guess maven artifacts are timing out. I'm in the middle of implementing the job scheduler integration and after that i'll setup jitpack for v2.

**Comment by ninjahoahong** [comment]
@yigit Thank you. I will try again then :D

**Comment by yigit** [comment]
Hi,

I've integrated JitPack for v2 and updated the README.
Lmk if you can give it a shot and whether it works or not. Thanks!

**Comment by ninjahoahong** [comment]
@yigit Hi, it is working now. Thank you so much.

**Comment by sriram-kakarala** [comment]
We are seeing this error again from today? Is the artefact available or completely removed?

**Comment by yigit** [comment]
it is released to just use production version.
