### ISSUE TITLE
Table job_holder_tags did not clean, when job is finish.

### ISSUE THREAD

**Issue by pzhangleo** [yigit/android-priority-jobqueue#109]
When a persist job is finish, it will remove form table job_holder.
But its tags remain in job_holder_tag.
So when will be these tags been removed from db?
Thank you very much.

**Comment by yigit** [comment]
they are not cleaned but I can implement it in V2. It was not thought in the initial design and was a bit tricky to implement in the current codebase. In V2, Job Manager is initialized in its own thread so I can easily run a cleanup query on startup. I'll implement this in v2.

**Comment by pzhangleo** [comment]
Thanks for your reply.
When will branch v2 be a stable api to use?

**Comment by yigit** [comment]
I'm close to releasing alpha. Actually one big blocker is changing the package name. I'll do it now so that you (and many others) can start using it now.

**Comment by yigit** [comment]
ok to do this I'll have to merge the job-scheduler. It is not well tested yet so I suggest not to use the JobScheduler API. Rest should be fine.

**Comment by yigit** [comment]
ok, i've completed repackaging, didn't push to v2 yet but you can use it via:

    repositories {
        mavenCentral()
        maven {
            url "https://jitpack.io"
        }
    }

    dependedencies {
        compile 'com.github.yigit:android-priority-jobqueue:move-packages-SNAPSHOT'
    }

**Comment by pzhangleo** [comment]
Thank you for your excellent job.
I will try it.
