### ISSUE TITLE
How avoid run next jobs of a group?

### ISSUE THREAD

**Issue by tebitoq** [yigit/android-priority-jobqueue#111]
Hi , I have two jobs something like that:

```
@Inject
JobManager jobManager;

public void login(String username, String password) {
        jobManager.addJob(new AuthenticateUserJob(username, password, GROUP));
        jobManager.addJob(new ProfileJob(GROUP));    
}

```

There is a way to avoid run the ProfileJob if the AuthenticateUserJob is canceled?

Regards.

**Comment by ArtemWidelab** [comment]
Why don't you add `ProfileJob` in `AuthenticateUserJob `?

**Comment by yigit** [comment]
As @ArtemWidelab suggested, it is better to do it inside the job when it succeeds.

**Comment by tebitoq** [comment]
@ArtemWidelab yes, the problem is some cases I not need call ProfileJob after AuthenticateUserJob, but sure maybe its the only solution.

Thanks.
