### ISSUE TITLE
NPE at JobManager

### ISSUE THREAD

**Issue by Sebosam** [yigit/android-priority-jobqueue#130]
Fatal Exception: java.lang.NullPointerException
       at com.c.a.a.f.a(JobManager.java:158)
       at app.b.t.a(LoginJob.java:63)
       at app.b.t.success(LoginJob.java:47)
       at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5118)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
       at dalvik.system.NativeStart.main(NativeStart.java)

Is it library bug?

**Comment by yigit** [comment]
idk because your stack trace is proguarded and you did not even mentioned which version you are using. 
Also seems like your job is making an async call but jobs are designed to be sync not async so something is definitely wrong in your Job (but there might be another bug in JobManager causing the NPE but cannot say anything from the obfuscated stack trace).

**Comment by Sebosam** [comment]
I using last version. Its my Job class
`public class LoginJob extends Job{

    public static final int PRIORITY = 100;
    Call<LoginResponse> loginCall;
    LoginModel model;
    Job job;

    public LoginJob(LoginModel model, Job job) {
        super(new Params(PRIORITY).requireNetwork().persist().groupBy("Login"));
        this.model = model;
        this.job = job;
    }

    @Override
    public void onAdded() {

    }

    @Override
    public void onRun() throws Throwable {
        loginCall = ApiClient.get().login(model);
        loginCall.enqueue(new Callback<LoginResponse>() {
            @Override
            public void onResponse(Call<LoginResponse> call, Response<LoginResponse> response) {
                if (response.isSuccessful()) {

                    for (Map.Entry<String, Boolean> entry : response.body().getPermissions().entrySet()){
                        switch (entry.getKey()) {
                            case "RCP":
                                WorkerApp.get().getStorage().setRcpPermission(entry.getValue());
                                break;
                            case "TIMESHEET":
                                WorkerApp.get().getStorage().setTimesheetPermission(entry.getValue());
                                break;
                            case "ABSENCE":
                                WorkerApp.get().getStorage().setAbsencePermission(entry.getValue());
                                break;
                        }
                        Utils.moduleNumbers += entry.getValue() ? 1 : 0;
                    }

                    WorkerApp.get().getStorage().setToken(response.body().getToken());
                    WorkerApp.get().getStorage().setQrCode(response.body().getQrCode());
                    WorkerApp.get().getStorage().setDeviceId(response.body().getDeviceId());

                    if(model.getUserName() != null) {
                        WorkerApp.get().getStorage().setUserLogin(model.getUserName());
                    }else{
                        WorkerApp.get().getStorage().setPhoneNumber(model.getPhoneNumber());
                    }
                    WorkerApp.get().getStorage().setUserPassword(model.getPassword());
                    switch(Utils.ExceptionState) {
                        case ExceptionState.LOGIN:
                            EventBus.getDefault().post(new LoginEvent(response.code()));
                            break;
                        case ExceptionState.GET_STATUSES:
                            WorkerApp.get().getJobManager().addJobInBackground(job);
                            break;
                        case ExceptionState.GET_INFO_FOR_USER:
                            WorkerApp.get().getJobManager().addJobInBackground(job);
                            break;
                        case ExceptionState.ADD_ABSENCE:
                            WorkerApp.get().getJobManager().addJobInBackground(job);
                            break;
                        case ExceptionState.ADD_AVATAR:
                            WorkerApp.get().getJobManager().addJobInBackground(job);
                            break;
                        case ExceptionState.GET_ABSENCE_INFO:
                            WorkerApp.get().getJobManager().addJobInBackground(job);
                            break;
                        case ExceptionState.SET_STATUS:
                            WorkerApp.get().getJobManager().addJobInBackground(job);
                            break;
                        case ExceptionState.CANCEL_ABSENCE:
                            WorkerApp.get().getJobManager().addJobInBackground(job);
                            break;
                        default:
                            EventBus.getDefault().post(new LoginEvent(response.code()));
                            break;
                    }
                    Utils.ExceptionState = ExceptionState.NOTHING;

                } else {
                    EventBus.getDefault().post(new LoginEvent(response.code()));
                }
            }

            @Override
            public void onFailure(Call<LoginResponse> call, Throwable t) {
                Log.i("LoginJob", "BLAD! : \n" + t.toString());
                WorkerApp.get().getJobManager().addJobInBackground(new LoginJob(
                        new LoginModel(nvm);
                EventBus.getDefault().post(new LoginEvent(-1));
            }
        });
    }
}`

**Comment by yigit** [comment]
by latest do you mean v2 alpha ? Can you also provide de-obfuscated stack trace?

Btw, you should be making the call sync not async and then handle the exception on shouldReRun method, there you can tell job manager to retry the job by a simple return. (see docs).

Also, you are re-adding the same job which you cannot. You need to create a new job even if you want to re-add it **unless** you use shouldReRun method to retry (which you should)

**Comment by Sebosam** [comment]
ahh sorry 1.3.5 updated maybe month ago ago. I rewrite (job in login its other job for relog in action to get token it isnt same job). Now i will use shouldReRun. Thanks for time i will msg when problem will not disappear.
