### ISSUE TITLE
Handle Multiple Job

### ISSUE THREAD

**Issue by hanhmh1203** [yigit/android-priority-jobqueue#134]
Hello Friend,
I have a question,
I have 4 job and it start with same time.
1. How to handle when finish all 4 job ?
2. How to know what job final finish.
Thanks so much!!

**Comment by hanhmh1203** [comment]
plz help me !! @yigit

**Comment by yigit** [comment]
it is not cool to write help me just after 11 hours!

Besides that, you can:

Create a job manager callback, assign it to the job manager,
Keep the list of jobs in the callback and remove them as they are done.

For example, here what we do in tests:

https://github.com/yigit/android-priority-jobqueue/blob/master/jobqueue/src/test/java/com/birbit/android/jobqueue/test/jobmanager/JobManagerTestBase.java#L273

**Comment by hanhmh1203** [comment]
so sad,
I don't understand, i don't know how to apply to my project.
My project used instance jobmanager, and I just add job by addJobInBackground.

**Comment by yigit** [comment]
Not sure what is confusing you. Here are the related docs:
http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/callback/JobManagerCallback.html

http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/JobManager.html#addCallback(com.birbit.android.jobqueue.callback.JobManagerCallback)

Btw, this is a v2 only feature, maybe thats why you are confused ?

**Comment by hanhmh1203** [comment]
ok, thanks @yigit  so much, I will try :)
