### ISSUE TITLE
Consider adding a saveState<T> method to jobs

### ISSUE THREAD

**Issue by benoitdion** [yigit/android-priority-jobqueue#137]
This would make what jobs decide to serialize a lot more explicit. It's especially useful when using injection where currently we have to carefully mark injected fields as transient. Also make writing custom serializer easier as there is no guessing what should be serialized and what shouldn't.

**Comment by yigit** [comment]
I guess you can enforce it for an app (have a custom interface and custom serializer) but I don't like the idea of enforcing it for all jobs since it introduces an inconvenience.

Are you trying to write a generic serializer to be published as a library?

**Comment by benoitdion** [comment]
Understood and makes sense. I just thought it'd be nice to have the extra safety but I guess it is a bit less convenient.

I wrote a gson serializer because I find json a better serialization format than the dreaded java Serializable.

**Comment by yigit** [comment]
i agree on json, actually something like kryo is even better but i didn't want to enforce another dependency. Closing this for now, my suggestion is to enforce it in your app via a base class / interface for all jobs.
