### ISSUE TITLE
Feature request: something along the lines of onPostRun() or onSuccess()

### ISSUE THREAD

**Issue by muntasirsyed** [yigit/android-priority-jobqueue#139]
It would be useful if there was a way to run code specifically when a job has successfully completed onRun() without cancel, something along the lines of onSuccess() that is called by the job just like onCancel() is called on cancel.

If this feature is already available in another way please do point me in the right direction.

**Comment by yigit** [comment]
If you are using v2, you can use the [JobManagerCallback](http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/callback/JobManagerCallback.html#onJobRun(com.birbit.android.jobqueue.Job,%20int)).

It has two related methods:
**onJobRun**: called right after job is run but before it is removed from/readded to the queue (depending on the result)
** onAfterJobRun**: called after job and after it has been re-added to the queue or removed from the queue (depending on the result)

You can also extend [JobManagerCallbackAdapter](http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/callback/JobManagerCallbackAdapter.html) not to implement all methods.

Lmk if this works.

**Comment by muntasirsyed** [comment]
This works great, thanks.
