### ISSUE TITLE
Download Job not persisted if app crashes or if exception thrown.

### ISSUE THREAD

**Issue by JimVanG** [yigit/android-priority-jobqueue#140]
I have a class that extends `Job` that is used to download large files. I need the download job to be persistent, but I can't get the download job to persist if the app crashes, or if it is terminated during the download process, or if the download task throws an `Exception`.

Here's my Download Job class:
``` Java
public class DownloadJob extends Job implements Serializable {
	private static final String TAG = DownloadJob.class.getName();
	// Higher is better.
	private static final int PRIORITY = 1000;

	private static final int BUFFER_SIZE = 5 * 1024;

	private String marketID;
	private String marketItemID;
	private String url;
	private String directoryPath;
	private String fileName;
	private AccessToken token;

	public DownloadJob(String marketID, String marketItemID, String url,
	                       String directoryPath, String fileName, AccessToken token) {
		super(new Params(PRIORITY).requireNetwork().persist().groupBy("download_job"));

		this.marketID = marketID;
		this.marketItemID = marketItemID;
		this.url = url;
		this.directoryPath = directoryPath;
		this.fileName = fileName;
		this.token = token;
	}


	@Override
	public void onAdded() {
		Log.d(TAG, "DownloadJob added to disk");
               // DownloadJob is always successfully added to disc.
	}

	@Override
	public void onRun() throws Throwable {
		Log.d(TAG, "onRun() DownloadJob called");
                // DownloadJob's onRun() is always called initially.
		ComponentName comp = new ComponentName(getApplicationContext().getPackageName(),
				DownloadJobService.class.getName());
		Intent intent = new Intent().setComponent(comp);
		ComponentName service =
				getApplicationContext().startService(intent);
               // Service starts successfully
		if (service == null) {
			Log.e(TAG, "Could not start service " + comp.toString());
		}
   //DownloadAsyncTask always starts successfully. But if the app crashes, terminates, or the
 //DownloadAsyncTask throws an Exception then the DownloadJob never restarts later, because it
//appears the Job is removed from the JobManager, I know this because if I do a jobManager.count() the
//count will be zero.
		new DownloadAsyncTask().executeParallel();

	}

	@Override
	protected void onCancel(int cancelReason) {
		Log.d(TAG, "onCancel() DownloadJob called");
	}

	@Override
	protected RetryConstraint shouldReRunOnThrowable(Throwable throwable, int runCount,
	                                                 int maxRunCount) {
		Log.d(TAG, "shouldReRunOnThrowable() DownloadJob called");
          //This is never called no matter what.
		return RetryConstraint.RETRY;
	}
```

So the problem is that the DownloadJob is not persisted if the app crashes, is terminated, or throws an `Exception` during the download process. `onAdded()` and `onRun()` are always called initially, but if the app is terminated during the process they're never called again, `onCancel()` and `shouldReRunOnThrowable()` are also never called after the crash/termination/exception.

It appears that the `DownloadJob` is removed from the `JobManager` during the crash/termination/exception, because when I later do a` jobManager.count()` the count is always zero, and the `DownloadJob` is never restarted.

Am I doing something wrong here? Should I not be starting an `AsyncTask` in `onRun()` -- should everything be synchronous in `onRun()`? Or could it be something else?

I can post my `DownloadAsyncTask` class if needed.

**Comment by mseshachalam** [comment]
Is it necessary to do the downloads in an AsyncTask here in the Job ? The Job is already a thread, I remember from yigit's comment on some issue, he says if we use the threads or such in Job's on run the JobManager wont be able to manage these.

**Comment by JimVanG** [comment]
@mseshachalam , I didn't know that `Job` was already it's own thread (I should of though...). I'll try and do the download synchronously since the `Job` is already it's own thread and see what happens. Thank you.

**Comment by yigit** [comment]
yep, what @mseshachalam said. Your job finishes as soon as run finishes so it is removed from the queue. I'll close this but feel free to re-open if it still does not work after you make the download job sync.

**Comment by JimVanG** [comment]
Commenting again to confirm this fixed the problem and that all work in `onRun()` should be synchronous. Thank you so much for working on this great library.
