### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by jonfinerty** [yigit/android-priority-jobqueue#143]
Hi,

I'm looking into using android-priority-jobqueue as a core part of my app's infrastructure. Functionality-wise it's looking like a great library. However I'm trying to work out how to test it.

I'm using Robolectric (like you do for testing it's internals), I'm wondering how to set up tests around a Job? Putting it through a JobManager causes threading issues (even in testmode), but creating and executing it standalone doesn't set up the job's ApplicationContext which it will need and I will have to re-implement the logic of when to call `shouldReRunOnThrowable` etc.

Any advice?

**Comment by jonfinerty** [comment]
Small update: at the moment I'm testing a job by setting it up in a JobHolder as follows:

```
JobHolder jobHolder = new JobHolder.Builder().job(job).priority(1).runningSessionId(1).createdNs(1).build();
jobHolder.setApplicationContext(RuntimeEnvironment.application);
jobHolder.safeRun(0);
```

This however doesn't let me test any behaviour in `onCancel`. So I might have to write my own simple retry logic around the saferun, but I don't want to end up writing my own jobmanager.

**Comment by yigit** [comment]
Hi, what did you end up using? We can add a WIKI page about testing individual jobs.

JobManager's own tests use JobManagerCallback class to wait until a job is done.

https://github.com/yigit/android-priority-jobqueue/blob/master/jobqueue/src/test/java/com/birbit/android/jobqueue/test/jobmanager/JobManagerTestBase.java#L274

usage: https://github.com/yigit/android-priority-jobqueue/blob/ca48bb3d9cf85bf61c60b88cfb196325c59e931a/jobqueue/src/test/java/com/birbit/android/jobqueue/test/jobmanager/NetworkJobWithFallbackTest.java
