### ISSUE TITLE
When job is onRun cannot be cancel

### ISSUE THREAD

**Issue by spirosoik** [yigit/android-priority-jobqueue#144]
Is that expectable or am I doing something wrong? I want even if the job is `onRun` to cancel this job.

btw it will help a flow chart with states and cases.

**Comment by yigit** [comment]
If you cancel a job while it is running, it will not be interrupted.
If it fails in the onRun method, it will be cancelled, if it completes successfully, it will work.

Trying to cancel a job while it is running is very problematic (java interrupts). 

I flow chart would be good though, I understand :).

Btw, what exactly are you trying to achieve here ?

**Comment by spirosoik** [comment]
hi @yigit I thought that it will be related with java interrupts but it's ok.

The flow chart will be great guys, you must add it for sure.

Imagive that I have two lists where you can upload images without waiting to upload it. So this is the usage by us for priority jobqueue ( we want also them to persisted and upload them later and stuff) but imagine that someone understood ohhh this was wrong and he tried immediately to cancel the job and he can't. So we remove the element from the list but after that we have an event state process which shows the image again because the job cannot be cancelled when is `onRun`. 

In general is UX so we fixed our UX to avoid such things and stuff.

**Comment by yigit** [comment]
When a job is cancelled while it is running, you can check `job#isCancelled` inside the onRun method and handle it manually (by dropping the request result etc).
