### ISSUE TITLE
Reorder jobs

### ISSUE THREAD

**Issue by rslama** [yigit/android-priority-jobqueue#145]
Hi is there any best practice how to reorder/change priority of already added job? Now I cancel existing job and add same with higher priority but it's little bit tricky. I would like have something like get job from queue and change priority without cancel/add.

**Comment by heitorpr** [comment]
Guuys. This issue would be very useful to me too. Time by time my pages take to long to load, and I do not want to cancel the jobs in background. Actually i want the jobs to complete after the jobs of the current activiy/fragment. So the user can see updated content very faster.

**Comment by yigit** [comment]
You can only change a job's priority when it fails via [RetryConstraint](http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/RetryConstraint.html).

@heitorpr for that use case, you may achieve that by having an incremental priority for each resumed activity. You can have a static priority counter that you increment in each activity resume and set the priority of UI related jobs using that priority.

**Comment by heitorpr** [comment]
Woooooow o.O. Thx Yigit!! I will try that approach!! :D
