### ISSUE TITLE
When does next job exactly gets executed?

### ISSUE THREAD

**Issue by niket-sminq** [yigit/android-priority-jobqueue#147]
Hi @yigit ,
Can you let me know when does next job starts executing if more than one job in queue?

Suppose I have 3 jobs in queue (grouped to run all jobs one by one sequential). 
Suppose first job's starts onRun() method
So when does second job will start its onRun() method? Is it like...When first job's onRun() completes its execution OR as soon as first statement in first job's onRun() starts?

Actually In my case I want to run second job only when first job's onRun() executes all its statement.

**Comment by gbhall** [comment]
"You can assign same groupId to these jobs and Job Manager will ensure they
run sequentially." Check out:
https://github.com/yigit/android-priority-jobqueue/wiki/Job-Configuration

**Comment by yigit** [comment]
it is called after the previous job is removed from the job queue (either completed or cancelled). The only case their order changing might be if you handle `shouldReRun` on the higher priority (or earlier submitted if priorities equal) job and give it a lower priority or set a delay in the shouldReRun callback and not apply it to the group.

When multiple jobs have the same group, JobManager guarantees that at most 1 of their onRun method will be running at a given moment.

Please close the ticket if this explanation is clear.

**Comment by niket-sminq** [comment]
okay got it, thanks for the quick reply. Closing this ticket. Thank you again.
