### ISSUE TITLE
Serialization/deserialization of annotated POJO seems to fail

### ISSUE THREAD

**Issue by Esardes** [yigit/android-priority-jobqueue#149]
Hello,
I have a simple POJO annotated to for LoganSquare purposes 
```
@JsonObject
public class Poll {
    @JsonField(name = "email")
    public String mail;
    @JsonField(name = "answer")
    public String answer;

    public Poll(){}

    public Poll(String myEmail, String mystring) {
        mail = myEmail;
        answer = mystring;
    }

    @Override
    public String toString(){
        return "Poll " + userEmail + " " + answer;
    }
}
```
I then do a simple job `PrintPollJob` where... well, I print the `Poll` object passed in the constructor
```
public class PrintPollJob extends Job {
private Poll poll;
public PrintPollJob(Poll aPoll) {
        super(new Params(PRIORITY).requireNetworkWithTimeout(10000));
        poll = aPoll;
    }
...
@Override
    public void onRun() throws Throwable {
            Log.d("My Job","Job finished with id " + this.getId() + " and poll " + poll);
    }
...
}
```
So, by default the object is not persisted, and if I run the following in my activity
```
public JobManager  jobManager = new JobManager((new Configuration.Builder(this)).build());
jobManager.addJobInBackground(new PrintPollJob(new Poll("doe@example.com","lalala")));
```
it will correctly print 

> My Job: Job finished with id [some UUID] and poll Poll doe@example.com lalala

Now if I do exactly the same thing, in the same conditions, but where I persist the job, i.e constructor becomes
```
public PostPollJob(Poll aPoll) {
        super(new Params(PRIORITY).requireNetworkWithTimeout(10000).setPersistent(true));
        poll = aPoll;
    }
```
multiple logs and manual tries seem to indicate that
1/ more often than not `onAdded` is called but not `onRun`
2/ when `onRun` is called, object `poll` is always `null` (the few times I got to that step, that was by reloading the app)

(using version 2.0.0-alpha2)

Any idea?

**Comment by yigit** [comment]
you need to mark the class serializable and it will work.

https://docs.oracle.com/javase/7/docs/api/java/io/Serializable.html

**Comment by Esardes** [comment]
thank you
