### ISSUE TITLE
Submitting job from AsyncTask

### ISSUE THREAD

**Issue by vinvinod** [yigit/android-priority-jobqueue#150]
Hi Yigit,

Is submitting a job from AsyncTask a bad way of using job queue?
If not,
    * If a job is submitted from AsyncTask, in which thread is the onAdded() callback called?
    * Should I use tools (like CountDownLatch) to make sure that AsyncTask doesn't return until the onAdded() is called?

I have gone through the wiki and faq, but could not come to a conclusion!

**Comment by mseshachalam** [comment]
Just giving my thoughts, might be wrong too.

It should not be a problem/bad way  to submit a job from AsyncTask (or from anywhere else). The JobManager is a singleton and Job processing is independent of where the Jobs are submitted from, i.e JobManager is responsible for its execution based on it configuration. OnAdded will be called on its own thread(by JobManager)

Why do you think its a bad way to submit a Job from AsyncTask ? Please share your observations.

**Comment by yigit** [comment]
In v1, `onAdded` was called on the thread job is added.
In v2, it is called on the JobManager's own thread. 

If you are just trying to offload job addition to non-main thread, just use `jobManager#addJobInBackground`. 

If there is other reasons, when you call `addJob` the method will return after `onAdded` is run on JobManager's thread.

**Comment by vinvinod** [comment]
From the documentation, this is the line which got me thinking
`Beware, onAdded() is called on the thread job was added.`
Suppose the thread that has called the job (in my case, from an asyncTask) no longer exits (doesn't have event loop anymore), I was wondering where the `onAdded` is run!

But now I get that onAdded is called on JobManager's thread.
Thank you both.

**Comment by yigit** [comment]
i've updated the WIKI, thanks.
