### ISSUE TITLE
Job cancel but it will reRun next time the app launcher

### ISSUE THREAD

**Issue by ZoroLu** [yigit/android-priority-jobqueue#151]
When a job is added with persist ,i call cancel before the job run,it work and the job is canceled.But when the next i launcher the app, the cancel job will reRun. i had set  shouldReRunOnThrowable to be RetryConstraint.CANCE, but it doesn't work.

**Comment by ZoroLu** [comment]
A job will cancel if throw an exception on run or cancel by manual,when it was canceled by manual,it should not reRun if cancel by manual.

**Comment by yigit** [comment]
When you cancel the job, are you receiving a result that verifies the job is cancelled?
Is it possible for you to create an app that reproduces your issue?

**Comment by ZoroLu** [comment]
Sorry for reply so late.Yes I received a result with cancel reason code 3,it will take some time to create an app ,i am busy these day and i will take an app that reporduces this issue some days later.Thank you, yigit.

**Comment by yigit** [comment]
When a job is removed, response comes after it is removed from disk. If you can send an app, that would help a lot figuring out the issue.
