### ISSUE TITLE
not restart when wifi enable

### ISSUE THREAD

**Issue by gaurnagchauhan** [yigit/android-priority-jobqueue#156]
i am using 'com.path:android-priority-jobqueue:1.1.2' for my job scheduler. it was working good. when i disable my wifi it stop but when i enable my wifi my job will not restart. how to i configure my jobManager in this scenario. please help

**Comment by yigit** [comment]
please share how you configure(crete) job manager. Also, 1.1.2 is quite old.

**Comment by gaurnagchauhan** [comment]
private void configureJobManager() {
        Configuration configuration = new Configuration.Builder(this)
                .customLogger(new CustomLogger() {
                    private static final String TAG = "JOBS";

                    @Override
                    public boolean isDebugEnabled() {
                        return true;
                    }

                    @Override
                    public void d(String text, Object... args) {
                        Log.d(TAG, String.format(text, args));
                    }

                    @Override
                    public void e(Throwable t, String text, Object... args) {
                        Log.e(TAG, String.format(text, args), t);
                    }

                    @Override
                    public void e(String text, Object... args) {
                        Log.e(TAG, String.format(text, args));
                    }
                })
                .minConsumerCount(1)//always keep at least one consumer alive
                .maxConsumerCount(3)//up to 3 consumers at a time
                .loadFactor(3)//3 jobs per consumer
                .consumerKeepAlive(120)//wait 2 minute
                .build();
        jobManager = new JobManager(this, configuration);
    }


 public FileUploadJob(Context context, com.ai.uploadservices.app.dal.File fileInfo) {
        super(new Params(0));
        mContext = context;
        mFileInfo = fileInfo;
    }

**Comment by mendhak** [comment]
Try this:

    super(new Params(0).requireNetwork());

**Comment by gaurnagchauhan** [comment]
Thanks mendhak. But this option i tested but then also not start uploading while i enable my wifi.

**Comment by yigit** [comment]
@gaurnagchauhan 1.1.2 is really old, can you move to v2-alpha3 or at least the latest 1.x release and test with it. You might also be missing 
`<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />`
Feel free to re-open the issue if these do not fix your issue. An app to reproduce the issue would be helpful.
