### ISSUE TITLE
Jobs Prioritization

### ISSUE THREAD

**Issue by vinvinod** [yigit/android-priority-jobqueue#158]
Hi,

Can I reserve a thread for the processing of higher priority task always!

A use case is this:
Job of Type-A are of low priority. Jobs of Type-B are of high priority. If the all the threads in the thread pool are busy with processing Type-A jobs, is there any way to make the newly submitted Type-B job to run immediately?

I can use multiple job manager instances for this. But is there any other way?

**Comment by yigit** [comment]
Sorry, JobManager does not have a way to reserve threads for particular jobs. You would need a separate JobManager for this.
