### ISSUE TITLE
« Unmetered network »

### ISSUE THREAD

**Issue by christophetd** [yigit/android-priority-jobqueue#159]
Hi, 

It was not clear to me how to require Wi-Fi connection for a job to be run. After a quick look in the source code, I noticed the `requiredUnmeteredNetwork` method in the `Param` class, but even after that I had to check in `NetworkUtilImpl` that this was indeed what I meant.

Since this is a feature that is quite important, I think it would be a good idea to talk about it somewhere (in the readme or the wiki). This would also encourage developers to use an unmetered network when dealing with non-urgent background tasks, and could save mobile data usage for the end users.

What do you think? I can submit a PR with a little more explanation about this, if it's OK for you

**Comment by yigit** [comment]
I would happy to receive a PR for this.
There is already a wiki for job configuration: https://github.com/yigit/android-priority-jobqueue/wiki/Job-Configuration
But maybe it is not very discoverable. Maybe I we can add a paragraph about unmetered network and link to there ?

**Comment by christophetd** [comment]
I'll take a look at it when I have time and will submit a PR :+1:
