### ISSUE TITLE
Integration with volley and okhttp post requests?

### ISSUE THREAD

**Issue by tuhin10** [yigit/android-priority-jobqueue#160]
Is it possible to use it with volley custom post request? I am sending string values in the request body.

`public class CustomPostRequest extends Request<JSONObject> {
    private Listener<JSONObject> listener;
    private Map<String, String> params;

    public CustomPostRequest(String url, Map<String, String> params,Listener<JSONObject> reponseListener, ErrorListener errorListener) {
        super(Method.GET, url, errorListener);
        this.listener = reponseListener;
        this.params = params;
    }

    public CustomPostRequest(int method, String url, Map<String, String> params,Listener<JSONObject> reponseListener, ErrorListener errorListener) {
        super(method, url, errorListener);
        this.listener = reponseListener;
        this.params = params;        
        setRetryPolicy(new DefaultRetryPolicy(10000,DefaultRetryPolicy.DEFAULT_MAX_RETRIES, DefaultRetryPolicy.DEFAULT_BACKOFF_MULT));
    }

    protected Map<String, String> getParams() throws com.android.volley.AuthFailureError {
        return params;
    };

    @Override
    protected Response<JSONObject> parseNetworkResponse(NetworkResponse response) {
        try {
            String jsonString = new String(response.data,
                    HttpHeaderParser.parseCharset(response.headers));
            return Response.success(new JSONObject(jsonString),
                    HttpHeaderParser.parseCacheHeaders(response));
        } catch (UnsupportedEncodingException e) {
            return Response.error(new ParseError(e));
        } catch (JSONException je) {
            return Response.error(new ParseError(je));
        }
    }

    @Override
    protected void deliverResponse(JSONObject response) {
        listener.onResponse(response);
    }
  }
`
`    CustomPostRequest jsonReq = new CustomPostRequest(Request.Method.POST,
            URL_POST, null, new Response.Listener<JSONObject>() {
        @Override
        public void onResponse(JSONObject response) {
               //Update ui
            }
        }
    }, new Response.ErrorListener() {
        @Override
        public void onErrorResponse(VolleyError error) {
            Log.e(TAG, "Error: " + error.getMessage());
        }
    }){
        @Override
        protected Map<String, String> getParams() throws AuthFailureError {
            Map<String, String> params = new HashMap<String, String>();
            params.put("key1", "value1");
            params.put("key2", "value2");
            return params;
        }
    };
    //Adding request to volley request queue
    App.getInstance().addToRequestQueue(jsonReq);`

And for uploading an image to the server i am using okhttp like this

```
`OkHttpClient client =  new OkHttpClient.Builder()
                .connectTimeout(30, TimeUnit.SECONDS)
                .writeTimeout(30, TimeUnit.SECONDS)
                .readTimeout(30, TimeUnit.SECONDS)
                .retryOnConnectionFailure(false)
                .build();`

`MultipartBody.Builder formBodyBuilder = = new MultipartBody.Builder()
                    .setType(MultipartBody.FORM)
                    .addFormDataPart("key_1", "value 1")
            .addFormDataPart("image_file", fileName, RequestBody.create(MEDIA_TYPE_JPEG, imageFile));

MultipartBody requestBody = formBodyBuilder.build();
  Request request = new Request.Builder()
                .url(URL_POST)
                .post(requestBody)
                .build();
        Call call = client.newCall(request);
        call.enqueue(callback);`
```

**Comment by yigit** [comment]
you can use job manager with any but you should use `sync` APIs not `async` APIs.
For example, when using retrofit, don't call `call.enqueue(callback);``, instead call `call.execute(callback);`
