### ISSUE TITLE
Running jobs synchronously

### ISSUE THREAD

**Issue by Shashank066** [yigit/android-priority-jobqueue#161]
I have multiple jobs made to handle different operations. Now there is one main job from which I would like to call other jobs in onRun(). The problem is jobs are designed to not block currently. Is there anyway to run them synchronously?

**Comment by yigit** [comment]
can you clarify further. Calling another job's on run does not make much sense in JobManager's context.
onRun is designed to be called by the Job Manager. Maybe in your case, it makes more sense to make those other jobs simple runnables and have 1 job that calls them synchronously.

Alternatively, if your only requirement is not running these jobs in parallel, you can check the grouping API.
https://github.com/yigit/android-priority-jobqueue/wiki/Job-Configuration

**Comment by Shashank066** [comment]
Actually, all I just wanted was the thread in which addJob is called to block until job completes. I had written a job for each task such as DownloadJob and UploadJob and tested them individually. Now when I run one main syncing job which is supposed to be doing downloading and uploading many times, running jobs synchronously would have been helpful. I could have simply called addJob for upload task wait for it to complete and after it completes carry on with uploading or downloading next file.
I understand that may not be possible as Job Manager has it's own queue. So, I refactored upload and download as methods instead of jobs. You can probably close this.
