### ISSUE TITLE
I want to run my job on wifi enable and stop my job on wifi disable. how i config my job and jobManager

### ISSUE THREAD

**Issue by gaurnagchauhan** [yigit/android-priority-jobqueue#162]

**Comment by yigit** [comment]
see: https://github.com/yigit/android-priority-jobqueue/wiki/Job-Configuration
`requireUnmeteredNetworkWithTimeout`

**Comment by IgorB10** [comment]
Hi @yigit, I don't see any API in Params class for `requireUnmeteredNetworkWithTimeout`. Can you please give me some hint how to use it.

`Version: 2.0.1`
