### ISSUE TITLE
JobManager in a Background Service

### ISSUE THREAD

**Issue by 3flex** [yigit/android-priority-jobqueue#171]
I'm sorry this if this is an obvious question but I'm a relative beginner at Android so hopefully someone can help (also if this should be on StackOverflow I can post there instead).

I want to make sure any queued jobs continue to completion/failure even if there are no visible processes.

My requirements are:
* Service must not start until a Job has been received
* Service must continue to run until queue is empty and no jobs are running
* Service must stop running once queue is empty and no jobs are running (or shortly after)
* If a new Job is added while queue is empty and no jobs are running, Service must either continue to run or start again if it has been stopped

Because JobManager, CallbackManager and the Service all operate on different threads, I'm not sure how best to accomplish this while avoiding any race conditions.

I'd like to know the right pattern to ensure this is handled in a robust way. I've looked online and searched the source code but haven't uncovered much. Of course I can run the service forever, but it won't be doing anything most of the time and would be unkind to other apps. Thanks to anyone who can help!

**Comment by yigit** [comment]
Why do you want to have a service running? If you are trying to make OS know that your app needs to do something:
If it is a background service, from the OS's perspective, it is not much different then not having anything.
If it is a foreground service, then there are OS limitations (showing a notification etc).

Having a background service will not change OS's decision to whether go idle (close network etc) or not. The proper way to do those is integrating with [JobScheduler](https://github.com/yigit/android-priority-jobqueue/wiki/Integration-with-JobScheduler-and-GcmNetworkManager) which you can with v2.
So, imho, you probably don't need to have it. But if you do, probably the best option is to rely on CallbackManager and count queries.

**Comment by 3flex** [comment]
Thanks Yigit.

JobScheduler or GCM Network Manager may be good solutions, but the jobs running are of a transactional nature and must start as soon as initiated by the user. I'm not sure those provide these guarantees, since they're designed to batch requests together at some future point in time.

Perhaps this isn't the right use case for this library?

**Comment by mseshachalam** [comment]
https://github.com/yigit/android-priority-jobqueue/wiki/Faq#why-not-use-just-a-service-

says
 ```
First of all, you can run Job Manager inside a service, it is completely up to you.
```
What does it mean ? @yigit could you please provide an example app with Job Manager in a service.

**Comment by yigit** [comment]
it just means you can create the JobManager by creating a service and stop/destroy it when service stops. The actual code (or job) still runs on another thread but this is the expected service behavior anyways (e.g. services don't get a special thread).
