### ISSUE TITLE
Provide an API to get Context

### ISSUE THREAD

**Issue by yigit** [yigit/android-priority-jobqueue#18]
It is common that jobs need a context and many people make a mistake by passing context to a persistent job.
Instead, we can add a `getApplicationContext` method to Job class and it can get it from JobManager.

**Comment by mseshachalam** [comment]
nice one +1

**Comment by mecid** [comment]
@yigit i am using DI for injecting Context and not only Context.

**Comment by yigit** [comment]
Yea, thats what we were doing in Path but not everybody is using DI so I thought this API would be useful.

**Comment by kamilwlf** [comment]
What is the role played by DI in getApplicationContext? Can you give link to a article or tutorial?

**Comment by yigit** [comment]
fixed in 1.3.2
