### ISSUE TITLE
Schedule Jobs in JobManager Without JobScheduler and GcmNetworkManager

### ISSUE THREAD

**Issue by dineshkumar-cse** [yigit/android-priority-jobqueue#180]
Hi,

How we do we schedule a job without JobScheduler and GcmNetworkManager? Due to limitations `version < Lollipop` & Play Service not available.

**Comment by yigit** [comment]
JobManager does not require them. They are only used as an addition to be able to wake up the application to run jobs.
For instance, if you create a job with 2 hrs delay, there is a good chance that your app will be killed by the OS. So JobManager can use schedulers to wake up the app in 2 hrs.

Without that integration, as long as your app is running, your jobs are run as usual.

**Comment by yigit** [comment]
Also, you can implement the Scheduler interface yourself if there is a similar service available on the devices you are targeting.
