### ISSUE TITLE
NetworkUtilImpl leaks NetworkCallback

### ISSUE THREAD

**Issue by mwajeeh** [yigit/android-priority-jobqueue#190]
I was using `NetworkUtilImpl` for my own purpose and noticed that it was leaking `NetworkCallback` also confirmed by using `com.squareup.leakcanary`.

My implementation 
```
NetworkUtilImpl network` = new NetworkUtilImpl(this);
int networkStatus = network.getNetworkStatus(this);
```
After above code executes, there is no way to undo `registerNetworkCallback()` and `registerReceiver`.

**Comment by yigit** [comment]
NetworkUtil is designed to live as long as JobManager lives (there is no unregister). 
It only uses application context internally so there is nothing it can leak. Can you add more details on what it is leaking ?

**Comment by mwajeeh** [comment]
Ok with little bit more investigation I was able to find leak:
If `listenNetworkViaConnectivityManager()` is called with activity context (by invoking `new NetworkUtilImpl(activityContext)`) then this method ends up leaking activity context.
 ```
@TargetApi(23)
    private void listenNetworkViaConnectivityManager(final Context context) {
        ConnectivityManager cm = (ConnectivityManager) context.getApplicationContext()
                .getSystemService(Context.CONNECTIVITY_SERVICE);
        NetworkRequest request = new NetworkRequest.Builder()
                .addCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET)
                .addCapability(NetworkCapabilities.NET_CAPABILITY_NOT_RESTRICTED)
                .build();
        cm.registerNetworkCallback(request, new ConnectivityManager.NetworkCallback() {
            @Override
            public void onAvailable(Network network) {
                dispatchNetworkChange(context);
            }
        });
    }
```

A leak safe implementation would be 
```
@TargetApi(23)
    private void listenNetworkViaConnectivityManager(final Context context) {
        final Context applicationContext = context.getApplicationContext();
        ConnectivityManager cm = (ConnectivityManager) applicationContext
                .getSystemService(Context.CONNECTIVITY_SERVICE);
        NetworkRequest request = new NetworkRequest.Builder()
                .addCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET)
                .addCapability(NetworkCapabilities.NET_CAPABILITY_NOT_RESTRICTED)
                .build();
        cm.registerNetworkCallback(request, new ConnectivityManager.NetworkCallback() {
            @Override
            public void onAvailable(Network network) {
                dispatchNetworkChange(applicationContext);//don't hold reference of context parameter
            }
        });
    }
```

> what do you mean by I'm using it for my own purposes? Are you creating an instance of it but not using with JobManager ?

Yes I am using it in my activity to detect if we have `METERED` or `UNMETERED` connection. I don't know how correct I am but even using application context whenever I will create instance of  `NetworkUtilImpl`, I will end up registering another listener. So in my case I must have a dispose method which would unregister all listeners. In short if you execute `new NetworkUtilImpl(applicationContext)` twice you have unused listeners attached to your application context (is it called leak too?).

**Comment by mwajeeh** [comment]
This is working fine for me:
```
public void dispose(Context context) {
        Context applicationContext = context.getApplicationContext();
        ConnectivityManager cm = (ConnectivityManager) applicationContext
                .getSystemService(Context.CONNECTIVITY_SERVICE);
        if (idleReceiver != null) {
            applicationContext.unregisterReceiver(idleReceiver);
        }
        if (connectivityChangeReceiver != null) {
            applicationContext.unregisterReceiver(connectivityChangeReceiver);
        }
        if (VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            cm.unregisterNetworkCallback(networkCallback);
        }
    }
```

**Comment by yigit** [comment]
i've shipped alpha5 with a similar change that always references app context. But there is still no unregister but we can also add it later. (the class is really intended for JobManager so unregister is not really required).
