### ISSUE TITLE
Persistence guarantee

### ISSUE THREAD

**Issue by LouisCAD** [yigit/android-priority-jobqueue#196]
Hi,

We already talked about this [here](https://github.com/yigit/android-priority-jobqueue/issues/172#issuecomment-223249754).
Now that alpha 4 is out (and even 5 now), which closes #174, is it possible to guarantee (and write it in the docs) that all persisted jobs created since v2 alpha 4 will be readable by all future releases of this library as long as the serialization we implemented is compatible? I mean, I guess the format is on us, but what about the directory where the jobs are stored, and the file names?

Such a guarantee would ensure apps using this library will have a slightly better UX.

Here's a little story of bad UX I had about 1 week ago explaining the why of my request:
> 
> I was writing an email in Inbox by Gmail Android app, my phone was plugged in and performing updates. The app was in the foreground as I was typing, but Inbox got updated anyway, and my draft wasn't saved. I gave up writing the email because of this, but there's for sure apps with more important jobs than saving a draft that may use this library (even more likely since your library is featured in your talks about android app architecture), and users won't care that their post with the perfect shot wasn't saved _because the dev updated the library in the latest shiny app update which couldn't read the serialized jobs because of an incompatibility issue._

**Comment by yigit** [comment]
As soon as I release v2, you'll receive this guarantee. It is called alpha mainly for this reason, I don't want to deal with backward compatibility which usually means deprecated methods etc. After v2, backward compatibility will be re-introduced going forward.
