### ISSUE TITLE
Throwable null in Job onCancel() method

### ISSUE THREAD

**Issue by donpwilson** [yigit/android-priority-jobqueue#197]
I'm not sure whether this is intentional or not:

When you return RetryConstraint.CANCEL in shouldReRunOnThrowable(), I was expecting the throwable from shouldReRunOnThrowable() to be passed to onCancel(). Instead, null is appearing alongside cancelReason = 5 (RUN_RESULT_FAIL_SHOULD_RE_RUN).

Certainly passing the throwable across would appear to be reasonable behaviour.

**Comment by yigit** [comment]
:: @dmarcato
