### ISSUE TITLE
How to create a recurring job?

### ISSUE THREAD

**Issue by lenguyenthanh** [yigit/android-priority-jobqueue#200]
Thanks Yigit for your awesome library. This is a question, not an issue for bug report.
My question is how to create a recurring job with JQ and it can runs even when user quit the app?

For example I want to post user location to server for each 5 seconds.

Thanks!

**Comment by LouisCAD** [comment]
@lenguyenthanh You'd better directly send the location to the server after each `onLocationChanged()` callback from Fused Location Provider

**Comment by yigit** [comment]
We don't have a way to add repeated jobs :/.
What you can do instead is to add a delayed job each time one finishes. DO NOT enqueue itself though, create a new job.

so something like this should work:

``` java
class LocationJob extends Job {
    static Location sLastSentLocation;
    public LocationJob() {
        super(new Params(MIN_PRIORITY).requiresNetwork().delay(TimeUnit.SECONDS.toMilliseconds(5)));
    }

    public void onRun() {
         Location location = LocationServices.FusedLocationApi.getLastLocation(
                mGoogleApiClient);
         if (location != null && (sLastSentLocation == null || sLastSentLocation.distanceTo(location) > SOME_LIMIT) {
                yourAppApi.sendLocation(location);
                sLastSentLocation = location;
         }
         jobManager.addJob(new LocationJob());
    }
}
```

This is not full code but i think you'll get the idea.

On a side note, 5 seconds seems very aggressive, what is your use case ?
Also, if you don't get the location permissions, this will keep re-running for no reason. You should probably handle that case as well.

**Comment by lenguyenthanh** [comment]
Thanks @yigit I got your idea :)
My use case is for some kind of car pool service, so I need to push driver location to server for tracking purpose. Do you have any idea for this one. 

And thank a gain for your side note, I will take care about it.

**Comment by yigit** [comment]
yea if it is a driver tracking, the phone is probably connected to charger so you are probably OK to do this. Maybe you should modify the delay depending on how much battery is left on the device if it is not charging.

**Comment by lenguyenthanh** [comment]
Thanks for suggestion.
