### ISSUE TITLE
How to make onRun of a Job run on UI thread?

### ISSUE THREAD

**Issue by codesForLiving** [yigit/android-priority-jobqueue#201]
Is there a way to specify the thread on which the Job will run?

**Comment by yigit** [comment]
you can provide a thread factory to control threads but you **cannot** run a job on UI Thread. This is against the design of this library. It should be used to run long running tasks that are not related to views.

If you are trying to pass the result onto main thread, use an event bus or some callback mechanism. See the sample app for example usage.

**Comment by codesForLiving** [comment]
okay. I was trying to have jobs for UI modifications. The UI Modifications have to wait for the previous Modification to finish. When a UI modification starts,  finishes, it sends out event on eventbus, and `jobManager` is started[it is stopped when a job's `onRun` is called]. That is why I was using Job queue for that.

I am currently posting on UI handler inside `onRun` of the Job. it works, but I was hoping for more elegant solution. If you know any other way, please let me know.

**Comment by yigit** [comment]
actually, thats a horrible way :(. The Job should be de-coupled from the UI. You should write it such that Job can stay alive forever even if the UI is gone / replaced etc. Having a UI handler reference in the Job defeats this purpose.

There are multiple ways to implement this de-coupled. I guess 3 of them would be:
a) Use a global eventbus. see the sample project
b) Use something like rx where the model to unsubscribe is well defined so that your UI code can unsubscribe from the job
c) Just use a simple Listener interface.

**Comment by codesForLiving** [comment]
> You should write it such that Job can stay alive forever even if the UI is gone / replaced etc

Generally, yes. But the only work that my `job` does is to modify the UI. They listen for completion of animations via eventbus. And then next `job` is started.

Actual work is being done in `Asynctask`(coded before I found this library), the `AsyncTask` returns the results. Users need visual cue as to what happened behind the scenes, which involves multiple independent UI modifications to be done, sequentially.

That is why I am using this library, I understand it is not what this library is meant for, but I couldn't find any other way to execute UI modifications in sequence.[the sequence is not fixed, but varies according to the result received by `AsyncTask`.]

**Comment by yigit** [comment]
does the work include any network call, disk access etc? (anything expensive).
If not, thats definitely not a proper use case for this library.
I think Asynctask might be appropriate for what you are trying to do. You can provide a single executor thread to the AsyncTask to make sure they run in sequence.
Also, you may want to take a look at RxJava.

**Comment by codesForLiving** [comment]
Yeah I considered using AsyncTask with single executor thread, but removing tasks of the corresponding activity from the thread after activity is destroyed[others instances of the same activity will be adding to the same executor thread], would be PITA.

I will be using priority-job-queuue only, for its ease.

Thanks for your help!!
