### ISSUE TITLE
Find Job by tag

### ISSUE THREAD

**Issue by panayiotis-andreou** [yigit/android-priority-jobqueue#203]
Hi @yigit, thanks for this excellent library

On version 1.3.5 i was overwriting the QueueFactory to be able to find jobs by tags using the api findJobsByTags

How can i implement this on v2 ? 
Can you send me an example of how to use findJobs api on a queue ?

Regards,
Panayiotis

**Comment by yigit** [comment]
you can do the same. Queue Factory API didn't change.
