### ISSUE TITLE
Use job to consistently transfer the data to peer

### ISSUE THREAD

**Issue by iammini5** [yigit/android-priority-jobqueue#204]
I have a task stay running to keep read the data from database and send them to another clients via udp socket, is there any support in job queue for this loop cases?

**Comment by yigit** [comment]
If this is something you want always to run, might just makes sense to implement it as a separate Thread, independent of JobManager.
What is the reason you want to use JobManager for this?

**Comment by iammini5** [comment]
Because i have to manager mulitple different tasks to run in different thread and monitor the error inside each thread to make them work in accordance, also i have to manage the retry and interval. I am trying to understand if the exception inside the job api can be used for this purpose.

**Comment by yigit** [comment]
Yea then I think you can use jobs for your atomic actions. Just make sure you keep the connection resources outside the jobs and provide them to the jobs when they are run (either via dependency injection or some other mechanism)
