### ISSUE TITLE
Our market does not have Google Play Services

### ISSUE THREAD

**Issue by mahuafactory** [yigit/android-priority-jobqueue#205]
how can I use this?

**Comment by mseshachalam** [comment]
This doesnt depend on play services. You need play services only when you want to work JobScheduler and GcmScheduler (which are from play services.)

**Comment by yigit** [comment]
To clarify, JobScheduler is in the framework, you don't need Google for that but it is API21 and above. You can also implement Scheduler API if there is a matching API in your market.
