### ISSUE TITLE
No API to limit the job inside a single consumer(thread)

### ISSUE THREAD

**Issue by iammini5** [yigit/android-priority-jobqueue#207]
I am curious if there is a way to limit my job running in a dedicated thread without sharing with other job, because i really want to make my job and its retry to be high priority by allowing malloc a dedicated thread(consumer) for it inside jobqueue.

**Comment by yigit** [comment]
Unfortunately no. You can provide your own thread factory but it is shared between all jobs.

**Comment by yigit** [comment]
Can you add more details about your use case?

**Comment by iammini5** [comment]
The use case is like this:
1. network sender job which fetch the data from the request from blocking queue 1 and retry if failed for every 300 ms, then wait for response from blocking queue 2.
2. network receiver job which listen for the response from server and enqueue the response into blocking queue 2.
3. Because both the receiver job and sender job need to run in a short time interval ( every 300 ms )
, i expect the 2 job can be run in the thread from job manager with the mininal cost.

**Comment by yigit** [comment]
If you want to dedicate threads to these, don't use JobManager for that because it does not provide you much. Seems like these are things that you want to keep alive as long as your app is alive. Is there a particular reason why you want to use JobManager?

**Comment by iammini5** [comment]
I would like to have my jobs(generate data and consume data) to have the execution interval(retry) more precisely so that it would lost any data or cause congestion, i could not find other library which can be used to control my  different tasks' life cycle and interaction more clearly like job manager.

**Comment by yigit** [comment]
i think your best solution is to write something custom by creating two threads and handling retry etc. One of main selling point for JobManager is the ability to efficiently share resources between multiple tasks which is definitely not what you want.

If you don't have time for that and don't mind the overhead, create a separate JobManager just for these 2 job types. Set group "a" when you create a sender job and group "b" when you create a receiver job. Threads may swap but at a given point in time, JobManager will have a thread available for each job type and they wont affect eachother. If you are using JobManager for other tasks as well, create another JobManager for them. Just make sure to give these 2 JobManagers separate ids in the configuration to that their databases won't conflict.

Again, this is not the best solution but might be the fastest for you in terms of maintenance and implementation time.
