### ISSUE TITLE
JOB retries again before previous job has finished execution

### ISSUE THREAD

**Issue by ankurt-optimus** [yigit/android-priority-jobqueue#208]
Hello,

I am using job queue for making my web request calls persistent. It works well in most cases but sometimes when a job is executing where i am making my network call synchronously, even when my job is not finished, more jobs start executing and i end up making more than one network call.

I have configured my job manager as follows : 

    Configuration configuration = new Configuration.Builder(this)
                .customLogger(new CustomLogger() {
                    private static final String TAG = "JOBS";

                    @Override
                    public boolean isDebugEnabled() {
                        return true;
                    }

                    @Override
                    public void d(String text, Object... args) {
                        Log.d(TAG, String.format(text, args));
                    }

                    @Override
                    public void e(Throwable t, String text, Object... args) {
                        Log.e(TAG, String.format(text, args), t);
                    }

                    @Override
                    public void e(String text, Object... args) {
                        Log.e(TAG, String.format(text, args));
                    }
                })
                .minConsumerCount(1)
                .maxConsumerCount(1)
                .loadFactor(1)
                .consumerKeepAlive(15)
                .build(); 

Here is our onRun() block : 

     public void onRun() throws Throwable {
        ServiceChatApi serviceChatApi = RetrofitFactory.getInstance().create(ServiceChatApi.class);
        Preferences pref = new Preferences(ApplicationFile.getInstance());
        Call<SPResult> resultCall =
        serviceChatApi.sendChatToFriend(pref.getLoggedInUserToken(), getParams());
        Response<SPResult> resultResponse = RetrofitFactory.handleRequestSync(resultCall);
     
        if (resultResponse.body() != null && resultResponse.body().getStatus() == 0) {
             Log.d(" ", "Processed Job");
        } else {
             throwException();
        }
      }

In our case, we are trying to send chats to server and we are ending up with repeated chats due to multiple executions in the job queue.

On Logging the execution of job queue, what we found is OnRun() is getting called twice or thrice before shouldBeRunOnThrowable is called like:

onRun() - job failed
onRun() - job failed
onRun() - job failed
shouldReRunOnThrowable()
shouldReRunOnThrowable()

where as the execution in my understanding should be as follows 
onRun() - job failed
shouldReRunOnThrowable()
onRun() - job failed
shouldReRunOnThrowable()

Any help would be much appreciated,
Thanks and Regards.

**Comment by yigit** [comment]
That seems weird because you've limited consumers to 1.
Where are you creating the JobManager? Is there any chance that it might be created twice ?

**Comment by ankurt-optimus** [comment]
i dont think that would be the case, i am creating my job manager in my Application class
    public class ApplicationFile extends Application implements LocationListener {
            public void onCreate() {
            // inside configureJobManger is code where i have set up my jobmanager.
                configureJobManager();
            }
    }

this issue usually doesn't happy in the happy flow of things, like when you're connected with a nice wifi all the time, things always starts acting weird when i am on a choppy or slow network or i manually bring the server down and bring it back up.

**Comment by ankurt-optimus** [comment]
I think I have narrowed down what the issue was, yes I do have 2 job managers :) I kept one job manager just to add my "SyncDataJob" which I used to perform periodic sync with my server and another Job manager was required for other activities like sending chats etc.

Now the reason why i created the (periodic) SyncJobManager was because i needed to know active running jobs in my SyncJobManager so that I could add syncDataJobs only when running jobs count is 0. I couldn't do this with a single job manager. 

Is this the expected behaviour? Because according to my understanding, JobManager for syncDataJob should just perform syncDataJobs and not jobs added to other JobManager.

I think since I have two job managers, onRun() method always runs twice after some delay. Logs -

```
07-19 20:22:30.600 - onRun()
07-19 20:22:30.770 - shouldReRunOnThrowable()
07-19 20:23:00.815 - onRun()
07-19 20:23:00.820 - onRun()
07-19 20:23:00.939 - shouldReRunOnThrowable()
07-19 20:23:00.956 - shouldReRunOnThrowable()
07-19 20:23:31.012 - onRun()
07-19 20:23:31.042 - onRun()
07-19 20:23:31.182 - shouldReRunOnThrowable()
07-19 20:23:31.186 - shouldReRunOnThrowable()
```

This order of execution fixed as soon as i removed the job manager for syncDataJobs. 

Since only one job manager can be started per application, can you please suggest a way to manage different kind of jobs which might require different configuration of the job manager.

**Comment by yigit** [comment]
It is OK to have multiple job managers but you have to give them different ids.
I'm guessing you are not giving them `ids` so they end up using the same database file.
http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/config/Configuration.Builder.html#id-java.lang.String-

Also, if you are trying to ensure there is only 1 copy of a job, you can use single instance parameter:
http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/Params.html#singleInstanceBy-java.lang.String-

**Comment by ankurt-optimus** [comment]
Thanks a lot, i missed out on some very important info. This seems to have fixed the issue.
