### ISSUE TITLE
Thowable in shouldReRunOnThrowable() method does not include StackTrace

### ISSUE THREAD

**Issue by donpwilson** [yigit/android-priority-jobqueue#224]
I am just getting the first line of the Exception / Error in the Throwable - no StackTrace.

I am using 2.0.0-beta2 and backtracked to 2.0.0-alpha3 because I thought I remembered seeing StackTraces. However, it's also missing in alpha3.

I'm not sure if this is a bug or if I must have changed something else to cause this. It's making it harder to debug issues in my app.

**Comment by yigit** [comment]
Hmm thats weird, I just catch the exception and pass it to `shouldReRun` as is. I'll check what can be done.

**Comment by yigit** [comment]
I've tried this with the sample application by throwing an exception from onRun and logging it in on Cancel and in shouldReRun.
Both of them have the stack trace:

https://gist.github.com/yigit/3f914c92085217c29a45d975df812a39

And here is the updated job code that throws the exception:
https://gist.github.com/yigit/97af1577adfeaede4cf6c8fa139ff92c

Maybe something is wrong with the part that generates the exception.
