### ISSUE TITLE
Run more than 1 queue

### ISSUE THREAD

**Issue by IlyaEremin** [yigit/android-priority-jobqueue#225]
In my app I have some object which has queue.
App could have couple of such objects.
I need to attach unique queue to each object.
Is there any ability to create several queue and distinct them, for example, by names.

**Comment by yigit** [comment]
Yes, you can have multiple JobManagers. Just give them a stable unique id in the configuration builder when you construct them.

http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/config/Configuration.Builder.html#id-java.lang.String-
