### ISSUE TITLE
Rerun job on user interaction

### ISSUE THREAD

**Issue by tuhin10** [yigit/android-priority-jobqueue#227]
In case of some error I am show a notification to the user that "job has failed, tap to retry" (from  onCancel() ). What I would like to have is if the user taps on the notification job should rerun. So, is it possible to run the same job from onCancel() ?

**Comment by yigit** [comment]
You need to create a new instance of the job and add it to the queue.
You cannot re-use the same job after it is cancelled.

**Comment by tuhin10** [comment]
Can you please provide any code sample on how to submit a new job from the cancelled job?

**Comment by yigit** [comment]
It is not any different than creating a new job and calling add job on the job manager instance. So you do it the same way you've created the job.

**Comment by tuhin10** [comment]
It's working great. Thanks for your help.

**Comment by chiragsharma991** [comment]
can we use request id/Tag  to retry any request.
