### ISSUE TITLE
Cancel and remove running job from JobManager

### ISSUE THREAD

**Issue by aritraroy** [yigit/android-priority-jobqueue#231]
I am using JobManager and is very satisfied with its overall performance and design.

I am just stuck on a small thing. I have a particular job running and I want to give the user the option to cancel that job by clicking that button.

Now I have two questions,

1) How do I get the currently running Job reference?
2) How do I cancel a running Job and completely remove it from the JobManager queue? (I found APIs to cancel pending jobs, not running)

Any help would be highly appreciated?

**Comment by yigit** [comment]
You cannot cancel a job that is running (inside the `onRun` method) because JobManager does not interrupt the threads.
But if that job fails, it will be cancelled. In other words, as soon as it leaves `onRun` block, it will be re-considered for cancelation.

If you want to be able to cancel the job while it is inside the `onRun` method, your job can check `isCancelled` field inside the `onRun` method and just throw an exception if `isCancelled` is `true`.

e.g.

``` java
onRun() {
    // do some operation
    if (isCancelled()) throw new RuntimeException("");
   // do more work
   if (isCancelled()) throw new RuntimeException("");
   // etc etc
}
```

**Comment by aritraroy** [comment]
Thanks for the info.

Is there a way to get the reference of the current active job running in the JobManager?

**Comment by yigit** [comment]
No. This is by design because you don't control job lifecycle and trying to access them directly is likely to create many hard to reproduce race condition bugs.

You could technically track running jobs by adding a JobManagerCallback but I don't recommend it. What is your reason to access the job ?

**Comment by aritraroy** [comment]
I would be uploading/downloading files using jobs. Now when the user wants to cancel a particular transfer, I need to cancel that job, but there is no way in your library to do so.

So, I need a reference of the currently running job and cancel the individual upload/downloads tasks inside these jobs so that the currently transfer is cancelled.

**Comment by yigit** [comment]
You don't need the job to cancel it. Indeed, there is no way to cancel it from the reference. Jobs are cancelled with tags which you assign when you create the job so you can cancel them using the tags.

**Comment by aritraroy** [comment]
Thanks. I already checked this. But as I mentioned before, each job would be making a network call and uploading/downloading files. So when the user decides to cancel the current upload/download, I need to cancel that particular network call explicitly so that I can resume it later using its active session.

I have solved this. I got the reference of a particular job using EventBus and used that reference to cancel the individual network transfers happening inside that job. It seems to work fine. Do let me know if there is a better approach to solve this.

Thanks.

**Comment by yigit** [comment]
If you need to call the cancel from another thread (in case onRun is blocked), seems like the only solution.
Alternatively, you can check `isCancelled` inside the `onRun` method to cancel the next request (in case it is chunks etc).

**Comment by aritraroy** [comment]
Thanks for the suggestion. Will surely try.

**Comment by chshp1234** [comment]
> Thanks. I already checked this. But as I mentioned before, each job would be making a network call and uploading/downloading files. So when the user decides to cancel the current upload/download, I need to cancel that particular network call explicitly so that I can resume it later using its active session.
> 
> I have solved this. I got the reference of a particular job using EventBus and used that reference to cancel the individual network transfers happening inside that job. It seems to work fine. Do let me know if there is a better approach to solve this.
> 
> Thanks.

hi，I had the same problem,when you get the reference,but how to cancel it?
