### ISSUE TITLE
Merge jobs.

### ISSUE THREAD

**Issue by Khang-NT** [yigit/android-priority-jobqueue#234]
Sometimes Jobs which have same endpoint in queue could be merged to one job/request and send to server (in case server provides two method: send single message, and send multi messages).

**Comment by yigit** [comment]
There is no built in logic to merge jobs and I don't have an immediate API on how to do this.
But you can use a single instance job,have the list of "messages" messages be persistent somewhere else and when this job runs, it will check the list and upload them based on how many messages it has.
