### ISSUE TITLE
discussion on nested (mult-step) jobs

### ISSUE THREAD

**Issue by ZakTaccardi** [yigit/android-priority-jobqueue#236]
How would you best implement nested or multiple step jobs within this library?

An example is payment processing for a restaurant order. Let's say `TipJob` depends on the `PayForFoodJob` (you tip after you pay), and both these jobs depend on the `CreateCreditCardDataJob` (so the same credit card can be reused for both paying for the food and the tip).

**Comment by benoitdion** [comment]
see #136

**Comment by yigit** [comment]
qq. what does the CreditCardDataJob do? Send the card details to server?

**Comment by ZakTaccardi** [comment]
Haha, yes. Totally a reproduction of #136.  Kill this issue

**Comment by ZakTaccardi** [comment]
Nested bitches. PS I've been drinking, <3 you yigit
