### ISSUE TITLE
Running multiple jobs in parallel

### ISSUE THREAD

**Issue by anupkunwar123** [yigit/android-priority-jobqueue#238]
If i wanted to run multiple jobs like say more than 4 jobs in parallel, then minConsumerCount(>4) is the only options? Will it leave so many threads doing nothings when there aren't any jobs that needs to be processed in later time? Question

**Comment by yigit** [comment]
4 idle threads won't be a big issue. Alternatively, you can also set `loadFactor` to 1 and set maxThreads to 4 but recreating threads also has a cost.

I think the solution depends on your usage patter of the JobQueue. If you get a burst of jobs once in a while, setting loadFactor to 1 with a small min consumer count makes sense.
If you have a more distributed usage patter, then min 4 consumers may make more sense.
