### ISSUE TITLE
JobManager and its id behaviour

### ISSUE THREAD

**Issue by IlyaEremin** [yigit/android-priority-jobqueue#239]
Scenario:
1. I create JobManager with id 1.
2. Add jobs with persist flag to it.
3. Immediately close app (slide from recent list) without waiting until job finished
4. Open app and create JobManager with id 1.
Expected: After creating JobManager should have all jobs added in p. 2.
Actually: JobManager in p. 4 has no jobs at all

What am I doing wrong?

**Comment by yigit** [comment]
it should. You are referencing to the Configuration#Builder#id right? Just double checking since it is a string not an integer.

Can you share your job configuration?
Also, are you sure the jobs been added and not completed? Can you add some delay to them to ensure this is the case ?

**Comment by IlyaEremin** [comment]
`Configuration.Builder builder = new Configuration.Builder(context).id(id).(other_params).build()`
After I add `Thread.sleep(60000)` on top of job `onRun` everything works fine... Need investigate my job deeply

**Comment by IlyaEremin** [comment]
@yigit is it possible that job remove after reaching `maxRunCount`?

**Comment by yigit** [comment]
No i think your job just completes before the app is closed since you get the expected output when you put a thread sleep on the `onRun` method.

**Comment by yigit** [comment]
Also yes jobs are auto-cancelled if they hit retry limit which is 20 by default but you can change in the Job's `getRetryLimit` method.

**Comment by IlyaEremin** [comment]
My job requires network to complete job, but when there is no network then it reach 20 times fails very soon and then auto-cancel triggered.
I think `network()` flag could help me with it. I write as soon as I will test it with `network()`.

**Comment by yigit** [comment]
cool. Feel free to close the ticket if it works as expected (it should :))

**Comment by IlyaEremin** [comment]
Yeap, 'requireNetwork()' made the trick.
