### ISSUE TITLE
Is this fork the new official maintained project?

### ISSUE THREAD

**Issue by mnesarco** [yigit/android-priority-jobqueue#24]
Hi, the path/android-priority-jobqueue repo looks like is abandoned and this fork seems to be active. Both artifacts are available in maven central:

com.birbit:android-priority-jobqueue:1.3.1
AND 
com.path:android-priority-jobqueue:1.1.2

May I assume this fork is the new active project?

Thanks, this is a great project!

**Comment by yigit** [comment]
Yes and no. I wrote almost all of this library when I was in path and now continuing development here. I cannot call it official though :) .
see: https://github.com/path/android-priority-jobqueue/issues/96

**Comment by mnesarco** [comment]
Thanks, I think maintained is more important than official.
