### ISSUE TITLE
Job waiting for required Network callback

### ISSUE THREAD

**Issue by longy26** [yigit/android-priority-jobqueue#241]
Hey,

is there any way to get a callback when a job was added, but is waiting for a required network?
I searched in the code but can't find a relevant callback.

Thanks in advance

**Comment by yigit** [comment]
No, there is no such callback. Most of the time JobManager does not even know the job exists if the job does not meet current criteria. What are you trying to achieve ?

**Comment by longy26** [comment]
Okay thought so. 
I'm trying to update my notification that an upload job has been queued but is still waiting for Wi-Fi network. 

I'm using EventBus to notify me when a job was added. Then I check jobmanager.count() for the number of jobs in the queue. But I'm not sure if they are just queued up because of to many jobs out whether they are waiting for Wi-Fi network. 

Thanks for your help.

**Comment by yigit** [comment]
Hmm, if you are interested in network state, you can create an instance of `NetworkUtil` and observe it and show your notification based on that.
But ofcourse, network comes and goes so you need to track it.

A proper implementation might be adding a `JobManagerCallback` which will get notified when a job is added and when a job is done (or running). It can combine those callbacks with `NetworkUtil` callbacks to decide whether to show or hide a notification.

**Comment by longy26** [comment]
Yes, i saw the `NetworkUtil` class. I'll just use that. Thanks for helping me out =)
