### ISSUE TITLE
Q: Priority for different queues

### ISSUE THREAD

**Issue by IlyaEremin** [yigit/android-priority-jobqueue#244]
Example: 
I create queue 1 and add tasks A, B, ..., Z  with priority 1, 3, 5, 7, ..., 55 to it.
Also, I create queue 2 and add tasks A1, B1, ... , Z1 with priority 2, 4, 6, 8, ... , 56 to it.
Q: do tasks affect on each others if they are in different queues (let's exclude CPU, network and storage impact)?
If does then in what order tasks are going to run if I start both queues at the same time?

**Comment by yigit** [comment]
Nope. Each JobManager instance is isolated and they have no interaction. They won't affect each other in any way.

**Comment by IlyaEremin** [comment]
Thanks
