### ISSUE TITLE
How to use custom serializer?

### ISSUE THREAD

**Issue by ZakTaccardi** [yigit/android-priority-jobqueue#246]
If I have classes that I want to de/serialize myself in a Job, how should I be doing it? An example of this would be great.

Marking such classes as transient so java doesn't try to de/serialize them? Or serializing to Strings manually and deserializing in `onInject(Job job)`

I'm using `Moshi`, so I can provide my own moshi instance in `onInject(Job job)` and then do my serialization/deserialization there.

**Comment by yigit** [comment]
https://github.com/yigit/android-priority-jobqueue/wiki/Job-Manager-Configuration
See title Job Persistence.

**Comment by ZakTaccardi** [comment]
oops, didn't see that. Thanks!
