### ISSUE TITLE
How to start a job after receiving high priority GCM message when dozing

### ISSUE THREAD

**Issue by markini** [yigit/android-priority-jobqueue#250]
Hello, I'm currently switching to the v2 version of this library.
Im using the default [NetworkUtilImpl](https://github.com/yigit/android-priority-jobqueue/blob/master/jobqueue/src/main/java/com/birbit/android/jobqueue/network/NetworkUtilImpl.java) as `NetworkUtil`.

After receiving a high priority GCM (data) message while dozing, the app acquires a wakelock and tries to start a new job (to download a few things).
The `NetworkUtilImpl` however states, that the device is dozing and the manager doesn't execute the job.

According to the [official documentation](https://developer.android.com/training/monitoring-device-state/doze-standby.html#using_gcm) this should however be possible: 
>GCM is optimized to work with Doze and App Standby idle modes by means of high-priority GCM messages. GCM high-priority messages let you reliably wake your app to access the network, even if the user’s device is in Doze or the app is in App Standby mode. In Doze or App Standby mode, the system delivers the message and gives the app temporary access to network services and partial wakelocks, then returns the device or app to idle state.

Do you have an idea to solve this kind of problem?

**Comment by yigit** [comment]
Hmm, we check if app is ignoring doze mode:
https://github.com/yigit/android-priority-jobqueue/blob/master/jobqueue/src/main/java/com/birbit/android/jobqueue/network/NetworkUtilImpl.java#L106

If that is not covering this case, I wonder if there is a way to check wake lock, on the other hand, the OS has the right to ignore wake locks when device is dozing.

I think for this case, you may want to implement a custom network util that bypass the check if the app is invoked from a high priority GCM message.

**Comment by markini** [comment]
> I think for this case, you may want to implement a custom network util that bypass the check if the app is invoked from a high priority GCM message.

Yeah, I guess will do this.
Thanks for your time :-)
