### ISSUE TITLE
How to run a job cycliqually (like a Timer) ?

### ISSUE THREAD

**Issue by anthony3444** [yigit/android-priority-jobqueue#252]
I would like to execute a job every x seconds. Is it possible with this library ?

Ps: this job will call a Facebook webservices.

Thank you very much

**Comment by yigit** [comment]
No, we don't have a built in way to do it.
Your only option is to post another instance of the job (**not the same one**) when completed.
e.g.

```java
public class MyJob extends Job {
    public MyJob() {
        super(new Params(priority).delay(10000));
    }
    public void onRun() {
        // do work
        jobManager.addJob(new MyJob()); // !!! new job, not this
    }
    public void onCancel() {
       // check cancel reason, if not cancelled by you, re-enqueue
    }
}

**Comment by anthony3444** [comment]
Thanks ! Perfect !
