### ISSUE TITLE
Unique Jobs in JobManager

### ISSUE THREAD

**Issue by aritraroy** [yigit/android-priority-jobqueue#253]
I am having a problem understanding and implementing this rather simple scenario using your library.

In my app, an user can add several files to be uploaded by clicking "Upload All" button and they will all be dispatched to individual jobs for uploading individual files. If there are 10 files to be uploaded then there are 10 jobs for them.

Now, the user may click the button again after some time and in that situation, those 10 jobs will be added once again in the job queue. If the user does that several times, the queue will be unnecessarily flooded with same jobs multiple times.

Now, is there any simple mechanism in your library which can add only unique jobs in the JobManager. Suppose if a particular job has been added once, and is in pending state then it can not be added again in the queue as its the same job.

Hope I could clear the scenario. 
Thanks.

**Comment by yigit** [comment]
You can create those jobs with single instance tag in params so that if the new job is added while in the queue, one will be cancelled.
Don't forget that this only works if the previous job is still in the queue. If it is already finished, JobManager will execute the new one happily :/.

http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/Params.html#singleInstanceBy-java.lang.String-

**Comment by aritraroy** [comment]
Thanks a lot. This solved the problem. Is there a way to silently cancel the job without firing onCancel()? Like I am showing some notifications in onCancel() which would be unnecessarily shown for this situation.

**Comment by yigit** [comment]
onCancel receives the cancel reason so you can check and not show the notification depending on the reason.
http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/Job.html#onCancel-int-java.lang.Throwable-

http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/CancelReason.html

**Comment by aritraroy** [comment]
Thanks a lot. This would solve my problem. 👍

**Comment by aritraroy** [comment]
I was trying this problem. I have used singleInstance for the particular jobs so that they only exist once.

Now I am facing an issue with it. When the user clicks the "Upload All" button (please refer to the first post above) all the available files are queued for upload. While these files are uploading, the user clicks the upload button again.

Now, for this time the jobs are again queued to run (should be cancelled) but after that if the upload button  is clicked several times, onCancelled is called with the proper reason (as expected).

But why does it get called for the second time? This should be not happening. The single instance might not be working properly. Any help?

**Comment by aftabsikander** [comment]
@aritraroy Did you solved this issue ?
