### ISSUE TITLE
Null job extras cause NullPointerException

### ISSUE THREAD

**Issue by JM-Agrimap** [yigit/android-priority-jobqueue#254]
Not sure exactly how I ended up with a job with null extras but it caused this NullPointerException when trying to look up the job UUID.
```
NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.util.ArrayMap.get(java.lang.Object)' on a null object reference
    android.os.BaseBundle.getString in BaseBundle.java::919
    com.birbit.android.jobqueue.scheduling.FrameworkScheduler.fromBundle in FrameworkScheduler.java::166
    com.birbit.android.jobqueue.scheduling.FrameworkScheduler.onStartJob in FrameworkScheduler.java::181
    com.birbit.android.jobqueue.scheduling.FrameworkJobSchedulerService.onStartJob in FrameworkJobSchedulerService.java::67
    android.app.job.JobService$JobHandler.handleMessage in JobService.java::126
    android.os.Handler.dispatchMessage in Handler.java::102
    android.os.Looper.loop in Looper.java::135
    android.app.ActivityThread.main in ActivityThread.java::5313
```

**Comment by yigit** [comment]
that is bad :/. Might be a framework bug. I can guard against this.

Any chance you can provide more information about your jobs etc? so I can try to reproduce this (in case it is related to the JobManager)

**Comment by JM-Agrimap** [comment]
This may have been caused due to upgrading from 2.0.0-beta-1 to 2.0.0, I can't say it for certain but the timing was within a couple of days after the version bump. This was a single occurrence and hasn't been reproduced in our testing since.

From what I can see PersistableBundle is created in FrameworkScheduler.toPersistentBundle() and should never be null in the current version unless android internally nukes it.

**Comment by yigit** [comment]
Actually, the PersistableBundle is not null here, rather its Parcel is broken probably because of the upgrade. I'm not familiar w/ internals of JobScheduler but it might also happen if the OS receives an update (unless JobScheduler uses xml bundles).

The exception happens in the unparcelling side, I can catch the exception thought that might hide some future bugs :/.
