### ISSUE TITLE
cannot save job to disk.

### ISSUE THREAD

**Issue by gauravwally** [yigit/android-priority-jobqueue#255]
I am handling server response to retry the job. It gives me the following error when i try to rerun the job.    java.lang.RuntimeException: cannot save job to disk(SqliteJobQueue.persistJobToDisk(SqliteJobQueue.java:107))
 Caused by: java.io.NotSerializableException: me.wally.android.WallyApplication

Base Job class.
public abstract class JobWithContext extends Job {
    Context context;

    public JobWithContext() {
        // default priority is pull
        super(new Params(JobPriority.SYNC_PULL).requireNetwork().persist());
    }

    public JobWithContext(Params params) {
        super(params);
    }

    public void setContext(Context context) {
        this.context = context;
    }

    public Context getContext() {
        return context;
    }

    @Override
    protected RetryConstraint shouldReRunOnThrowable(Throwable throwable, int runCount,
                                                     int maxRunCount) {
        // An error occurred in onRun.
        // Return value determines whether this job should retry running (true) or abort (false).

        if (throwable.getCause() instanceof Exception
                && throwable.getCause().getMessage() != null
                && throwable.getCause().getMessage()
                .equals("token expired")) {
            // TODO check why the server is not returning "WWW-Authenticate" header
            return RetryConstraint.RETRY;
        }
        else if (throwable.getCause() instanceof Exception && throwable.getCause().getMessage() != null
                && throwable.getCause().getMessage()
                .equals(Constants.serverError)) {
            return RetryConstraint.RETRY;
        }
        else {
            return RetryConstraint.CANCEL;
        }

    }

    public SharedPreferences getSyncPreferences() {
        return SyncPreferences.with(getContext()).getSyncPreferences();
    }

    // Just so we don't need to add on every job class
    public void onAdded() {

    }

    @Override
    protected void onCancel(@CancelReason int cancelReason, @Nullable Throwable throwable) {
        EventBus.getDefault().post(new SyncJobErrorEvent());
        // Job has exceeded retry attempts or shouldReRunOnThrowable() has decided to cancel.
    }
}

AccountsLoadJob.java
public class AccountsLoadJob extends JobWithContext {
    public static final int PRIORITY = JobPriority.SYNC_PULL;

    public AccountsLoadJob() {
        super(new Params(PRIORITY).requireNetwork().persist());
    }

    public AccountsLoadJob(String groupId) {
        super(new Params(PRIORITY).requireNetwork().groupBy(groupId).persist());
    }

    @Override
    public void onRun() throws Throwable {
        long timestamp = System.currentTimeMillis();
        WallyAPIClient.getInstance(getContext()).loadAccounts(
                new Date(getSyncPreferences().getLong("accounts_sync", 0))
        );
        getSyncPreferences().edit().putLong("accounts_sync", timestamp).apply();
    }
}

Application class 
 private Configuration getJobManagerConfiguration() {
        return new Configuration.Builder(this)
                .customLogger(customLogger)
                .minConsumerCount(1)//always keep at least one consumer alive
                .maxConsumerCount(3)//up to 3 consumers at a time
                .loadFactor(3)//3 jobs per consumer
                .consumerKeepAlive(120)//wait 2 minutes
                .injector(new DependencyInjector() {
                    @SuppressWarnings("deprecation")
                    @Override
                    public void inject(Job job) {
                        if (job instanceof JobWithContext) {
                            ((JobWithContext) job).setContext(getApplicationContext());
                        }
                    }
                })
                .build();
    }

**Comment by yigit** [comment]
The exception is clear, you cannot serialize the application class.
On the other hand, you don't need to do that `JobWithContext` thing. Jobs already have a getApplicationContext method that JobManager sets.

http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/Job.html#getApplicationContext--

**Comment by gauravwally** [comment]
Thanks a lot. It works.
