### ISSUE TITLE
Service not initializing on app closure

### ISSUE THREAD

**Issue by ilansr** [yigit/android-priority-jobqueue#257]
Hi,
I am attempting to use priority-jobqueue in order to continue running the jobs also post-app closure.
For this i have done everything required on your wiki page https://github.com/yigit/android-priority-jobqueue/wiki/Integration-with-JobScheduler-and-GcmNetworkManager

However, after application closure, the service never gets instantiated (I've added logs to the onCreate method which never get hit)

Also, your TwitterClient app has same configuration but it too does not instantiated the service.
I have tested it on a Marshmallow device, so I would expect it to use  "MyJobService.java"

Am am doing something wrong? Please advise further.

Thanks!
Ilan

**Comment by yigit** [comment]
JobManager only wakes up the app to run jobs if there is a job that is:
a) persistent
b) requires network or has significant delay.

On top of this, JobManager tries to batch these into 15minute intervals (depending on the Job's delay) to avoid waking up the app too many times.
