### ISSUE TITLE
Exception: Only the original thread that created a view hierarchy can touch its views.

### ISSUE THREAD

**Issue by anthony3444** [yigit/android-priority-jobqueue#258]
Hi guys!

I have this job to fetch local contacts (on mobile) : 

```
public class FetchLocalContactsJob extends Job {

    public interface OnGetLocalContactsListener {
        void onGetLocalContactsResult(FriendsList response);
        void onGetLocalContactsFailure();
    }

    public static final String TAG = HelpUtils.makeTag(FetchLocalContactsJob.class);

    private OnGetLocalContactsListener mListener;

    public FetchLocalContactsJob(OnGetLocalContactsListener listener) {
        super(new Params(Priority.HIGH));
        mListener = listener;
    }

    @Override
    public void onAdded() {}

    @Override
    public void onRun() throws Throwable {
        boolean add;
        FriendsList friends = new FriendsList();
        ....
        mListener.onGetLocalContactsResult(friends);
    }

    @Override
    protected void onCancel(@CancelReason int cancelReason, @Nullable Throwable throwable) {
        mListener.onGetLocalContactsFailure();
    }

    @Override
    protected RetryConstraint shouldReRunOnThrowable(Throwable throwable, int runCount,
                                                     int maxRunCount) {
        return RetryConstraint.CANCEL;
    }
}
```

I call this job from an Activity like that:

```
MyApplication.getInstance().getJobManager().addJobInBackground(
                    new FetchLocalContactsJob(new FetchLocalContactsJob.OnGetLocalContactsListener() {
                @Override
                public void onGetLocalContactsResult(FriendsList response) {
                    ...
                }

                @Override
                public void onGetLocalContactsFailure() {
                    ...
                }
            }));
```

The **first call** works perfectly. But if I do a new call (in this same Activity context), there is this error:

> E/JOBS: error while executing job com.xxxx.jobs.FetchLocalContactsJob@5326f030
                                       android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.

I can't understand why, thanks for your support !

**Comment by yigit** [comment]
This has nothing to do with JobManager. Jobs are executed on a background thread so by calling the callback on a background thread, you are accessing views on a background thread.

Instead, you should post it to a main thread handler (use an eventbus etc). Also, keeping a listener that has strong reference to views is a bad idea since the Job may live longer than the UI. You should either use an event passing mechanism OR use weak references to do this.
