### ISSUE TITLE
Interrupt running job

### ISSUE THREAD

**Issue by rafaelekol** [yigit/android-priority-jobqueue#26]
In JobManager in comments you wrote:
```
Note that, if any of the matching jobs is running, this method WILL wait for them to finish or fail.
```
Inside the job we have video compressing and video uploading code, so it can take really long time to accomplish this kind of job. We want our user to be able to cancel jobs.
Can I interrupt the running job, without waiting for finish or fail?

**Comment by yigit** [comment]
There is no way to interrupt it as in Java thread interrupt but you can manually do it.
While computing the compression, in each step or so, you can check `Job#isCancelled` and if it returns true, just return from the job w/o completing the compression.
