### ISSUE TITLE
Proguard

### ISSUE THREAD

**Issue by mhmtk** [yigit/android-priority-jobqueue#260]
Is there a proguard file for this lib?

Thanks :)

**Comment by jemshit** [comment]
?

**Comment by h-sadegh** [comment]
?

**Comment by jemshit** [comment]
i have only protected my Job classes from obfuscation and it works well with Proguard enabled. Not sure if it is necessary. So, no Proguard rules specific to this lib.

**Comment by mhmtk** [comment]
Well i've obviously solved my problem and closed this issue the day I opened it.

**Comment by kishaningithub** [comment]
@mhmtk Can you post your solution ? I am getting errors like

```
Warning: com.birbit.android.jobqueue.network.NetworkUtilImpl$2: can't find superclass or interface android.net.ConnectivityManager$NetworkCallback
```
