### ISSUE TITLE
Disclaimer in V1 to V2 Migration Doc 

### ISSUE THREAD

**Issue by kalpeshp0310** [yigit/android-priority-jobqueue#267]
I think bellow disclaimer should be removed as V2 is in production now.

> DISCLAIMER:
> 
> This is a WIP document. I've been a bad kid and didn't take enough notes while implementing V2 so some things might be missing. Please send pull requests and I'll keep the document up-to-date.

**Comment by yigit** [comment]
done. Thanks!
