### ISSUE TITLE
Feature request: single instance check applied if job is currently running

### ISSUE THREAD

**Issue by ckirkman** [yigit/android-priority-jobqueue#269]
If a Job with a given single id in its onRun() method when an additional Job with the same single id is created, the second job will be added to the queue. If a group id is also set, the second job will wait until the first job has exited onRun() before entering its own.

I have several cases where I would like to be able to configure the behavior to cancel the second job when it is added while a first job with the same single id is currently running.

Right now I'm maintaining my own list of actively running Jobs to check against before adding a new Job, but this feels redundant since I know this library is already keeping track of the same information.

**Comment by yigit** [comment]
Instead of keeping a list, you can also call getJobStatus to do that.  In terms of changing the behavior, I'll consider it under #268.

**Comment by ckirkman** [comment]
Thanks for the consideration!

To be clear, I probably should have said I'm maintaining my own list of Job IDs as I am calling getJobStatus. My particular cases are just ones where I wasn't checking on Job status otherwise.
