### ISSUE TITLE
Feature Request: Param to restrict job to certain API level

### ISSUE THREAD

**Issue by joaomgcd** [yigit/android-priority-jobqueue#270]
For example, I want to have a Job that only works on API level 25 or above. It would be nice if I could simple set a parameter for that and don't have to worry about it when queuing the Job from my code.

Thanks for the great library!

**Comment by yigit** [comment]
I understand it might be necessary time to time but i think it is outside the scope of this library since the API level of a device almost never changes.
Sorry about it but I don't think it is a necessary addition.
