### ISSUE TITLE
Persistent jobs

### ISSUE THREAD

**Issue by jemshit** [yigit/android-priority-jobqueue#271]
Wiki says:

> Persistence Sometimes, it is very important to ensure a job runs, no matter what happens to the app. (crash etc :) ). In this case, you can mark the job as persistent and Job Manager will take care of it. If your app crashed for some reason or gets killed by the OS, next time it re-opens, Job Manager will try to re-run it. 

Cant we run jobs in the background, independent from app lifecycle, even app is killed or crashed, job must run without stopping after they start ?! Above quote says library reschedules it when app is reopened, i want job to be independent from app lifecycle.

**Comment by yigit** [comment]
You cannot. Jobs run in the same process and OS kills the process. FYI when app goes to the background, jobs still run but if process dies, this library cannot do anything.
