### ISSUE TITLE
Using Volley in synchronous mode: TimeOutException appears sometimes

### ISSUE THREAD

**Issue by anthony3444** [yigit/android-priority-jobqueue#275]
Hi,

I call in all my jobs some Volley requests in synchronous mode. Sometimes there is a TimeOutException which appears with no logical behavior.

I saw this excellent article last week about your awesome library : [here](https://solidgeargroup.com/android-priority-job-queue-background-tasks)

And at the end ("tip" section) there is : "Never work with Volley sync requests inside a job, use Retrofit ones instead."

So I would like to know your opinion about that, and if Volley is forbidden to use with your library,

Thank you very much,

**Comment by yigit** [comment]
From JobManager's perspective, it does not matter (as long as the request is sync).
I personally never used volley on production so cannot comment on that.
Used Retrofit, is pretty good.

**Comment by dingbuoyi** [comment]
@anthony3444 

If it's caused by the Volley caches requests issues, you can make your own Volley, totally removed the cache layer from Volley,  I have done that and it works pretty well in my project.
