### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by jemshit** [yigit/android-priority-jobqueue#276]
1. How to know if all jobs are finished ? E.g for showing completed message notification?
2. Should i call `jobManager.stop()` before calling `jobManager.cancelJobsInBackground()` ? Because in FAQ it is not called
3. Is cancelling Job will clear it from queue, so it wont restart if i call start() on JobManager?
4. Any method, callback to get number of jobs in queue with some specific Tags? Or to get count asynchronously? (my intention is to find if job is running in JobManager then don't add it, otherwise, add the job to jobManager)
5. Will there be any problem if i start any new Thread in any of JObManagerCallback methods, like doing sth with my db in new Thread in `onAfterJobRun()` . Code:
```java
@Override
    public void onAfterJobRun(@NonNull Job job, int resultCode) {
        new Thread(new Runnable() {
            @Override
            public void run() {
                  android.os.Process.setThreadPriority(android.os.Process.THREAD_PRIORITY_BACKGROUND);
                  ... // Synchronous DB job here
            }
        }).start();
}
```

**Comment by yigit** [comment]
1) There is no notification for that. For a certain set of jobs, you can use a job manager callback to get notified when they are finished. You can see how tests do that [here][1]

2) Stopping JobManager means no other job will run (after currently running ones either fail or complete). Cancel cancels particular list of jobs and does not touch others. These two are unrelated. So no, you don't have to call stop after calling cancel.

3) Yes. Cancelling a job removes it.

4) Nope. You can get the [Job Status by id][2].
[1]: https://github.com/yigit/android-priority-jobqueue/blob/master/jobqueue/src/test/java/com/birbit/android/jobqueue/test/jobmanager/JobManagerTestBase.java#L274

**Comment by jemshit** [comment]
1) So only way is to keep counter when adding and removing it on done, i can use exact same method above i believe?
2) Does stop() clears job from queue, e.g if i stop then start again on different instances of JobManager, will it continue downloading ?

**Comment by yigit** [comment]
1) Yes. Keep in mind that this does not handle the case of a persistent job that might run after an process restart.

2) No STOP does not clear. There is a method for what you are trying to do if you check the docs. http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/JobManager.html#clear--

**Comment by jemshit** [comment]
1) i will keep counter in some storage for persistent jobs, so it should work i believe
2) `cancelJobsInBackground` seems more suitable than `clear`, `clear` does not have callback.

**Comment by shawnlinboy** [comment]
The `Job Status by id` is generated by `this.id = UUID.randomUUID().toString();`,not the `tag`??? How can I get the status???
