### ISSUE TITLE
2 Questions

### ISSUE THREAD

**Issue by kuno** [yigit/android-priority-jobqueue#278]
Sorry for the silly title 😭 

1, Is this lib support periodic jobs, e.g running a job for every 1 min in the background.

2, Can this lib can be used inside China ? Since we all knew that GCM service has banned in China.

**Comment by lenguyenthanh** [comment]
1. You can look at the answer here: https://github.com/yigit/android-priority-jobqueue/issues/200

2. You can use this library every where, but with GSM is banned, you can not use this with GSM integration.

**Comment by yigit** [comment]
FYI, if there is a matching service for GCM functionality, you can implement the Scheduler API.

**Comment by kuno** [comment]
@lenguyenthanh 

I want double check that no with GSM been banned in China. The GSM integration can not using inside China. Which means this lib do not work with pre-lollipop devices ?

Is that right ?

**Comment by yigit** [comment]
As the wiki says, the library **does not** depend on GCM. So it works fine in China.
It only uses GCM for an additional feature where it can wake up the process depending on some constraints. This is completely optional. ([related wiki][1])

If there is a similar service, you can implement the `Scheduler` API to get the similar functionality in china.

[1]:https://github.com/yigit/android-priority-jobqueue/wiki/Integration-with-JobScheduler-and-GcmNetworkManager

**Comment by kuno** [comment]
@yigit 

Thank for the very useful reply.

Previously  I was using `android-job` in my app, but the author told me weeks ago that on Android N, the minimal interval  for periodic job has forced to 15 minutes. 

But my app required run some job at the interval as small as 1 minute. 

Dose `android-priority-jobqueue` has such constraints on Android N devices ?

**Comment by yigit** [comment]
JobManager does not have an API to run a job repeatedly, you have to manually add it. A job is retried only if it fails (and retry time can be adjusted in the `shouldReRun` callback) .
Because we don't depend on the system, no there is no time limit.

**Comment by kuno** [comment]
Another question:

In #200, you mentioned a way to make a repeated jobs, which from my understanding is the job that restart itself constantly. 

This bring me a question, Can a job manager stop and then restart this repeated job >

**Comment by yigit** [comment]
there is no API to stop a job, you can only stop the job manager, which will finish currently running jobs and won't start anything else. Please check the javadoc.
