### ISSUE TITLE
Passing callback interface inside job

### ISSUE THREAD

**Issue by jermainedilao** [yigit/android-priority-jobqueue#287]
This is my job constructor:
`MyJob(int priority, MyJobCallback callback);`

and this is how I called it
`jobManager.addNewJobInBackground(10, new MyJobCallback(){
   ....
})`

now when my job is executed `onAdded` gets called but it doesn't proceed to `onRun`.

**Comment by yigit** [comment]
If the job is persistent, you cannot do this because your callback instance `probably` cannot be serialized. Also, job may not be ready to run (`params`).
Please provide more details, a sample projectetc so that i can understand what is going on.

**Comment by jermainedilao** [comment]
Oh yeah. My bad. I haven't thought of that. Thanks for the response!
