### ISSUE TITLE
How do you compare with Evernote android job library

### ISSUE THREAD

**Issue by athkalia** [yigit/android-priority-jobqueue#291]
Hello,

Looking into your library and the evernote one https://github.com/evernote/android-job
Seems like with your library I have to handle the scenario of API < 21 and no google play services on the phone. Is that the case? 

Also an open question to anyone that has researched both libraries, any suggestion on what I should go for?

Cheers,
Sakis

**Comment by yigit** [comment]
See the wiki:
https://github.com/yigit/android-priority-jobqueue#priority-job-queue-vs-job-scheduler-vs-gcmnetworkmanager-vs-

afaik, AndroidJob is just a wrapper around scheduler. This library does not rely on them, runs jobs itself. Uses schedulers just to be able to wake up the process.

**Comment by athkalia** [comment]
Thanks for the reply pal. 
Evernote's library will schedule either with JobScheduler, GcmNetworkManager or manually if neither is available (for example API < 21 and no google play services on the phone).
A quick slide presentation: 
https://speakerdeck.com/vrallev/scheduling-background-job-on-android-at-the-right-time

I guess both you library and evernote's are comparable in terms of feature sets.

Love your conference vids btw, keep it up : >

**Comment by barykaed** [comment]
Just a quick note to time travellers looking for slide deck mentioned earlier, the working URL is now 
https://speakerdeck.com/vrallev/scheduling-background-job-on-android-at-the-right-time-1
