### ISSUE TITLE
Cannot set a Job from JobHolder after it is sealed

### ISSUE THREAD

**Issue by puneetkkala** [yigit/android-priority-jobqueue#292]
Hi,

Can someone please help me on how can I avoid this issue?
Cannot set a Job from JobHolder after it is sealed.

> Non-fatal Exception: java.lang.IllegalStateException: Cannot set a Job from JobHolder after it is sealed.
       at com.birbit.android.jobqueue.Job.updateFromJobHolder(Job.java:131)
       at com.birbit.android.jobqueue.JobHolder$Builder.build(JobHolder.java:419)
       at com.birbit.android.jobqueue.JobManagerThread.handleAddJob(JobManagerThread.java:131)
       at com.birbit.android.jobqueue.JobManagerThread.access$000(JobManagerThread.java:35)
       at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:225)
       at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
       at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:220)
       at java.lang.Thread.run(Thread.java:818)

Thanks
Puneet

**Comment by yigit** [comment]
are you adding the same job instance twice ?

**Comment by puneetkkala** [comment]
Yeah, I was doing that. Thank you very much for helping me, it is resolved now. 👍

**Comment by puneetkkala** [comment]
No, I am not adding the same job instance twice now. The error is still happening.

**Comment by puneetkkala** [comment]
Should I switch back to some previous version?

**Comment by yigit** [comment]
no, we've not seen this error before, sth else is going wrong.
Can you provide more details or try to reproduce it in a sample app?

**Comment by yigit** [comment]
btw, the exception is very clear, are you sure you are not re-adding the same job instance?
I don't think there is any bug here.

https://github.com/yigit/android-priority-jobqueue/blob/58fc9dfc63f1358b32b26a262a81e2b98e6441ae/jobqueue/src/main/java/com/birbit/android/jobqueue/Job.java#L130

**Comment by puneetkkala** [comment]
```
public static DemoJob job;
public static void a() {
  if(job == null)
    job = new DemoJob();
}
public static void b() {
  if(job == null)
    job = new DemoJob();
}
public static void c() {
  if(job == null)
    job = new DemoJob();
}
```

**Comment by puneetkkala** [comment]
This is the code I am using to avoid multiple instances.
Most of the crashes are happening when there is very low RAM (about 10%-20%)
Can this be because of the RAM?

**Comment by puneetkkala** [comment]
The methods a, b, and c are called by other different methods on regular intervals.

**Comment by yigit** [comment]
what happens after if(job == null) job = new Job(); 
If it is like this:

```
if (job == null) {
   job = new Job();
}
jobManager.addJob(job);
```

Then you are adding the same job multiple times.

Even if you are adding only once, if these are called from multiple threads, you may still add the same job multiple times.

**Comment by puneetkkala** [comment]
Sorry for the late reply
Resolved the issue by these changes:
```
public static void a() {
  DemoJob job = new DemoJob();
  jobManager.addJob(job);
}

public static void b() {
  DemoJob job = new DemoJob();
  jobManager.addJob(job);
}

public static void c() {
  DemoJob job = new DemoJob();
  jobManager.addJob(job);
}
```

**Comment by chiragsharma991** [comment]
hi, some one can help me on how to retry request any time using string TAG ?
 
whenever i know "shouldReRunOnThrowable" but it is call instant time i want to use retry manually.
