### ISSUE TITLE
How to start a job only if non is running

### ISSUE THREAD

**Issue by MFlisar** [yigit/android-priority-jobqueue#293]
Is it possible to only start a job with a tag once? If the job is already running, I would like to avoid starting a second one with the same purpose... I even want to avoid queuing one in this case...

Can I somehow find out if a job with the same tag (or alternatively id) is already running or waiting to run?

In v1 I managed this logic myself, is this still necessary for what I want?

**Comment by yigit** [comment]
you can do with singleInstance tags.
https://github.com/yigit/android-priority-jobqueue/wiki/Job-Configuration

**Comment by MFlisar** [comment]
Not what I want, but thanks. If I want to start the FIRST job only and all subsequent calls should do nothing, even if the first job already runs (in my case especially then) I have to track queued/running jobs myself, which is not a big deal anyway...
