### ISSUE TITLE
A Job is run one more times without throw exception or calling

### ISSUE THREAD

**Issue by nghiavkht** [yigit/android-priority-jobqueue#297]
Hello,
I'm using Jobqueue for  sending data to RES service and facing below issue.

This is flow step:
0. Action save happen on UI => Save some data to DB which will be sent to server when job is run.
1. Add new job to Jobmanager
2. Job's constructor method is called
3. Job's onRun method is called to load data from DB and attach to ResAPI
4. Right after onRun 1st method is called, a new onRun is called and run in paralell
=> my service is call at the same time to service to add new record into DB => ERROR happen

This bug is happens randomly 50% if I save and sync multi object, down to 10% if save and sync once

Please check my below code and log
[log_error_duplicate_job_nghiavkht.zip](https://github.com/yigit/android-priority-jobqueue/files/675516/log_error_duplicate_job_nghiavkht.zip)

Many thanks!

**Comment by yigit** [comment]
One possible problem I can see in your code is that your `JobQueueManager`'s `getInstance` method is not synchronized so if it happens to be called in 2 threads at the same time, it may create 2 job managers.

That is still unlikely to happen 50% of the time but also in the logs I'm seeing 2 different queue IDs for the job manager (`queue_CONSTRAINT_CHANGE_160` and `queue_CONSTRAINT_CHANGE_155`). The number at the end is the ID. This queue is created only once so should not have 2 ids.

Can you sync getJobManager and try again?

If it is still happening, can you update the logger to print the current thread name and id as well?

Btw, on a side note, you should remove the thread creations in `JobQueueManager`. You are already calling `addInBackground`, that is safe to call on the main thread.

**Comment by nghiavkht** [comment]
Hi there,
Thank for your feedback, I've fixed all issue you listed.
But my issue still happens.

Please note that: There are two queue ID because I add 2 different jobs to queue at the same time, they are updateOrderJob and updateInvoiceJob

Please check log file and new code attached

Thank in advance!

**Comment by nghiavkht** [comment]
if you don't mind, could you add my skype at nghia.nguyentien89.
Thanks
