### ISSUE TITLE
Can this library be used as a substitute of AlarmManager

### ISSUE THREAD

**Issue by ashwanikumar04** [yigit/android-priority-jobqueue#307]
Hi,
Thanks for this awesome library.
This is more of a question than an issue.

Can we use this library as a substitute of AlarmManager to schedule job say
1. Daily
2. At a specific date
3. After every 4 hours etc

Thanks,
Ashwani

**Comment by yigit** [comment]
Unfortunately no, job queue does not support repeated scheduling and it is not planned. I'm open to pull requests though.
