### ISSUE TITLE
Observe why a job cannot be run yet

### ISSUE THREAD

**Issue by ZakTaccardi** [yigit/android-priority-jobqueue#311]
Given a `singleInstanceId` - I'd like to know *why* a job is in the `JobStatus#WAITING_NOT_READY` state. (i.e -> which job params are not yet met).

Is this possible?

**Comment by yigit** [comment]
Nope sorry. Giving such information about the internals of JobManager creates inconvenient dependencies. We would need to log why each job is not running but these decisions are made even w/o loading the job. Converting read  queries into writes would add unnecessary load so I'd rather not do this.
Sorry :/.
