### ISSUE TITLE
Job is running even if job manager hasn't start

### ISSUE THREAD

**Issue by lucas34** [yigit/android-priority-jobqueue#312]
Hi,

Even If I don't call jobManager.start() my job will still be executed how to prevent the job manager to start. I want to start the job manager at a specific point in my app. 

This is mostly for the test cases.

I assume by default the job manager will "auto start". So I end up calling stop() just after build. It's working fine for my tests. I think in the builder we should add something like .autoStart(boolean). Which is true by default. Will be less error prone.

Lucas.

**Comment by yigit** [comment]
I'm ok with the builder property. Would you be interested in sending a PR ?
