### ISSUE TITLE
how to persist a job which uses context object ??

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [yigit/android-priority-jobqueue#318]
one of my job needs context object. If i use context object in a job, i can not make that job persist. Because for persisting all objects needs to implement serializable and for context object i can not implement serializable.

Is there a solution to this problem ??

**Comment by yigit** [comment]
Job already has a method to get the ApplicationContext.
http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/Job.html#getApplicationContext--

And if your job depends on Activity context, you are doing it wrong since Activity Context is volatile and you don't own it.
