### ISSUE TITLE
Realm Integration.

### ISSUE THREAD

**Issue by KrishHari** [yigit/android-priority-jobqueue#320]
I would like to replace the Sqlite implementation of persistence with Realm. How can I achieve this. I couldn't find any configuration for this. Any help is appreciated

**Comment by aftabsikander** [comment]
+1

**Comment by ckirkman** [comment]
See this issue: #265 

You'll have to implement the JobQueue interface and then use your RealmJobQueue in a custom QueueFactory implementation and set the queueFactory when building your JobManager.

**Comment by KrishHari** [comment]
thank you for the response. I will try it out :)
