### ISSUE TITLE
Increase the priority of already added jobs

### ISSUE THREAD

**Issue by doomtrooper** [yigit/android-priority-jobqueue#325]
I want to increase the priority of the job on some condition such as the JOB is added again, The increase of priority is there on retry functionality.

**Comment by yigit** [comment]
you cannot. you can add a job with the same single instance id and with higher priority to cancel the previous one.

**Comment by yigit** [comment]
you need to be careful w/ race conditions though (e.g. the job you are trying to replace might already be finished)
