### ISSUE TITLE
Client timed out while executing (no jobFinished received)

### ISSUE THREAD

**Issue by surlac** [yigit/android-priority-jobqueue#326]
Thanks for the great library!

I'm using it to schedule and execute long-running tasks (e.g. download/upload/process large file).
Suddenly I'm getting following on Android M:
` I JobServiceContext: Client timed out while executing (no jobFinished received). sending onStop. `
and then all consumers stuck doing nothing.
How would I fix/avoid this error?

**Comment by yigit** [comment]
Hmm, job manager should not care about this at all. After that point, the OS will not give any guarantees on keeping your app alive though :/.
Are you saying that job manager stops working after this?
What happens to your long running job, is it getting stuck or finishing?

**Comment by surlac** [comment]
Turned out it's a problem on my side - job execution stuck on I/O (FileOutputStream.write), and after 15 mins system decided that job timed out and throw `Client timed out`. This explains why all consumers stuck, since they were also waiting on I/O.
Thanks yigit. Closing this issue.

**Comment by vktaras** [comment]
Hello.
How did you solved this issue?
I have the same one.
