### ISSUE TITLE
Jobs are not run when the phone is connected to Wifi

### ISSUE THREAD

**Issue by jauneshortcut** [yigit/android-priority-jobqueue#328]
I have a job that uploads an images to the server. Unmetered network is required to run this job (job is configured with requireUnmeteredNetwork()). When these jobs are created offline and then Wifi is turned on, the jobs are not staring to run "by them selves". I have to restart the app to get the jobs started. What might be the reason/solution?

**Comment by cipson** [comment]
I also noticed this issue on Android 6.0 phone(Motorola pure edition), but works correctly on Android 5.1(Nexus 4). Looks like network callback in the newer OS is not working.

**Comment by LuigiPapino** [comment]
maybe are you using the batch mode? In that case you have ti wait the specified amount of time, usually 15 minutes

**Comment by jauneshortcut** [comment]
Thank you for your answer @LuigiPapino , it seems to have solved the problem. I reconfigured my JobManager: 
builder.scheduler(FrameworkJobSchedulerService.createSchedulerFor(this, MyJobScheduler.class), false); 
Adding **false** did the trick!
