### ISSUE TITLE
Question: rerunning Job from async web request callback

### ISSUE THREAD

**Issue by ruthvik947** [yigit/android-priority-jobqueue#329]
Hi! I have a question:

A little background: I'm using Retrofit to execute an asynchronous request in the onRun method of a Job. I've implemented a callback that handles success and failure scenarios. Unfortunately, this callback won't allow me to throw an Exception to the outer (onRun) method, which means shouldReRunOnThrowable() is never called. 

My question: Is it ok to explicitly call shouldReRunOnThrowable(throwable, getCurrentRunCount, getRetryLimit) myself in the failure callback? If not, what can I do in this scenario?

Any help will be greatly appreciated. Thank you!

**Comment by yigit** [comment]
Just use the sync callback of retrofit. When your job returns, JobManager assumes it is competed.
For whatever reason, if you cannot use the asnyc callback, you can lock your onRun method until it returns.

**Comment by ruthvik947** [comment]
I'm looking into sync requests now, thanks Yigit.

**Comment by abdymm** [comment]
hai @ruthvik947 , can you please provide youre code for this one ? to throw an exception inside the failure method on retrofit ? i have same issue

**Comment by ruthvik947** [comment]
@abdymm, I decided to use synchronous requests since there seemed to be no way for the exceptions to not be consumed by async callbacks. Sorry I can't be of more help.

**Comment by abdymm** [comment]
hey @ruthvik947 , now i decided to use synchronous requests too . Thanks
