### ISSUE TITLE
Changing job params dynamically

### ISSUE THREAD

**Issue by cipson** [yigit/android-priority-jobqueue#330]
I am building an background uploader which using job queue to schedule upload jobs. My app also has a toggle switch for selecting metered and unmetered network. Users can toggle it whenever they needed. 

if i have a lot of pending jobs which are created for unmetered network, then user selecting metered network, how i can change the pending jobs to metered network.

Currently i am cancelling all jobs and recreate them, but if i have thousands of jobs, its taking time. 
Any suggestions?

**Comment by yigit** [comment]
You can provide a custom NetworkUtil when creating the job manager and there you can fake it :). This will affect all jobs thought but will probably be fine in your use case.

**Comment by cipson** [comment]
Thanks @yigit , i think that can solve the problem, but there is an issue around it.

My plan was to use listener.onNetworkChange(getCustomNetworkStatus()) to notify job manager when user toggle the metered/unmetered button. but setListener(NetworkEventProvider.Listener listener) is never called. I thought Job Manager will call this to register network changes.

http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/network/NetworkEventProvider.html#setListener-com.birbit.android.jobqueue.network.NetworkEventProvider.Listener-
