### ISSUE TITLE
[Question] Job persist + reboot

### ISSUE THREAD

**Issue by fchauveau** [yigit/android-priority-jobqueue#334]
Hi,

Quick question about usage. 
I create some jobs with execution date in the future and set them as persistable.
When a reboot phone job don't seem to be correctly restarted at phone startup. They only are restarted when I start the app. 
So am I wrong in my configuration or is it the normal behavior of the lib ?

thx

**Comment by LuigiPapino** [comment]
Have you added the permission RECEIVE_BOOT_COMPLETED?
try to post your configuration.
last time that I tried it worked well

**Comment by fchauveau** [comment]
Yes permission is added.

I just tried with twitter sample add, tasks are not relunched a boot.
For testing with twitter sample app : 
- Turn off data on device
- Add some message (they appear in wating list)
- Reboot
- Turn on data
-> Message are not sent but all requierment are ok.
- Start sample app
-> Message are sent immedialtly

**Comment by LuigiPapino** [comment]
Disable the  batch mode when you configure the JobManager, or wait 15 minutes.
Just tried now, and it's working fine.

You can use tools like Stetho to look into the database and check that the job is persisted.

**Comment by kpradeepkumarreddy** [comment]
how to disable batch mode ?
