### ISSUE TITLE
onRun() run repeatedly

### ISSUE THREAD

**Issue by donpwilson** [yigit/android-priority-jobqueue#336]
I found in my app testing using 2.0.0 that I had a case in one of my (non persistent) Jobs that, after an onAdded(), onRun() was run repeatedly, failing somewhere in the process but not throwing any messages into the runlog. My understanding is that shouldReRunOnThrowable() should be called whenever onRun() fails for any reason but this was not the case here. I know this because all of these methods are logged when called. I suspect that the underlying problem was that I had lost my internet connection but this generally leads to  shouldReRunOnThrowable() being called.

I don't want to attempt reruns if the internet connection is lost. Should I set a persistent variable within the Job to check for reruns or might there be a bug here, either on your or my side? I've since updated to 2.0.1

Let me know if you need more details. Thanks

**Comment by yigit** [comment]
just mark the job as requires network but there is still a chance network will be lost in between we checked network status and the job starts.
You should not need to do anything special for this but we won't retry your job w/o calling shouldReRun. You can check the logic here:

https://github.com/yigit/android-priority-jobqueue/blob/master/jobqueue/src/main/java/com/birbit/android/jobqueue/Job.java#L242

**Comment by donpwilson** [comment]
I don't want to mark the job as requiring the network because I prefer it to fail (and inform the user) rather than wait indefinitely. It is set up to retry 3 times first.

I agree that your code shows that  shouldReRunOnThrowable() is always run before a retry. 

So I remain perplexed that something happened which should not be possible. I'll keep a watch to see if it ever happens again. Meanwhile, I'm closing this issue as I can't see that there's anything you can do.

**Comment by donpwilson** [comment]
For the record, I've found the problem. It's a stupid mistake of mine. I'd changed the number of arguments in the logging message in shouldReRunOnThrowable() without changing the expected number in the string message. When an exception in onRun() was thrown, a further exception was thrown in shouldReRunOnThrowable() so my retry logic in that method wasn't called. The Job was therefore rerun the default number of times.
