### ISSUE TITLE
Is it possible to cancel a running job ?

### ISSUE THREAD

**Issue by arvind010** [yigit/android-priority-jobqueue#337]
Hi,
I am trying to cancel a already running job from notification bar with a stop button using below code 

`ApplicationFile.getInstance().getJobManager().cancelJobsInBackground(null, TagConstraint.ANY, jobTag);`

I am adding tag on job as below
`super(new Params(PRIORITY).requireNetwork().persist().addTags(jobTag));`

But My job's `onProgressUpdate` method keeps getting called.

I am initializing job manager with 
`Configuration configuration = new Configuration.Builder(this)
                .customLogger(new CustomLogger() {
                    private static final String TAG = "JOBS";

                    @Override
                    public boolean isDebugEnabled() {
                        return true;
                    }

                    @Override
                    public void d(String text, Object... args) {
                        Log.d(TAG, String.format(text, args));
                    }

                    @Override
                    public void e(Throwable t, String text, Object... args) {
                        Log.e(TAG, String.format(text, args), t);
                    }

                    @Override
                    public void e(String text, Object... args) {
                        Log.e(TAG, String.format(text, args));
                    }

                    @Override
                    public void v(String text, Object... args) {
                        Log.v(TAG, String.format(text, args));
                    }
                })
                .minConsumerCount(1)//always keep at least one consumer alive
                .maxConsumerCount(1)//up to 3 consumers at a time
                .loadFactor(1)//3 jobs per consumer
                .consumerKeepAlive(0)//wait 2 minute
                .id("JobManager")
                .build();`

Thanks 
Arvind

**Comment by LuigiPapino** [comment]
If the job is already running, the cancel can't stop the execution.

I think you have to stop the running , when you receive the `onCancel` callback, or checking the `isCancel`. How to do depends on your implementation of `onRun`

Documentation: https://github.com/yigit/android-priority-jobqueue/wiki/Canceling-Jobs
