### ISSUE TITLE
How to make the queue refuse to accept the task

### ISSUE THREAD

**Issue by hnty545** [yigit/android-priority-jobqueue#338]
Hello! I do very much work in the thread to consume resources, Android release of resources is very slow to accept the queue quickly, resulting in a lot of queuing tasks, it is easy to OOM. Can you set up more than a task to wait, and then discard or reject the task?
——————————————————
您好！我在线程里做非常消耗资源的工作，android释放资源很慢，接受队列的速度很快，导致排队的任务非常多，很容易OOM。可以设置超过多少任务等待，则抛弃或拒绝接受任务吗？

**Comment by yigit** [comment]
Not sure what you mean but are you trying to have limit on the number of jobs that can be queued? I don't think it is a good feature but you can implement it by writing your own queue factory and giving it to the configuration builder.

**Comment by hnty545** [comment]
Like BlockingQueue, the maximum cache capacity
