### ISSUE TITLE
Timeout for requireNetwork

### ISSUE THREAD

**Issue by malvinstn** [yigit/android-priority-jobqueue#339]
Is it possible to have a timeout for `param.requireNetwork`?
eg. the job will wait for 10s for network. If there's still no network after 10s, it will fire cancel/ retry the job.
Thoughts?

**Comment by malvinstn** [comment]
Tried using `param.overrideDeadlineToRunInMs` which will force the Job to run regardless of the Network status.
But subsequent retry no longer respects the `param.requireNetwork`.
Not sure if this is the intended behavior.

**Comment by yigit** [comment]
yep, that parameter means if that much time passes, ignore the constraints and run.
I think you are looking for [overrideDeadlineToCancel](http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/Params.html#overrideDeadlineToCancelInMs-long-).

**Comment by malvinstn** [comment]
Thanks. I think `overrideDeadlineToCancel` should do the work.
