### ISSUE TITLE
How to cancel a job if network condition no longer met?

### ISSUE THREAD

**Issue by liamheneghan** [yigit/android-priority-jobqueue#340]
I have a job that I'm adding to the JobManager that has the following parameters

```
final Params params = new Params(0)
				.requireUnmeteredNetwork();
```

I've found that `onCancel` is not called if I disable WiFi and switch to Cellular data. Is it my responsibility to check inside the running job that these conditions are still met?

In this case would it be most appropriate to have some broadcast receiver for network state changes and call cancel on the job - then inside the `onRun` return early/cancel?

I think I'm looking for the equivalent of `[onStopJob](https://developer.android.com/reference/android/app/job/JobService.html?utm_campaign=adp_series_job_scheduler_092216&utm_source=medium&utm_medium=blog#onStopJob%28android.app.job.JobParameters%29)` like in the Android framework JobScheduler.

Thanks

**Comment by yigit** [comment]
yea unfortunately we don't check for constraints after starting the job which seems bad for this case.
We could add a callback when constraints are no more matched but we cannot cancel because constraints may become re-available (so we can re-run the job).
So even if we add this API, your Job will have to check for it an cancel itself (and re-enqueue). seems bad:/. Or maybe we can create a special exception where job can say "i want to run later" and we'll re-enqueue it. wdyt ?

**Comment by liamheneghan** [comment]
Thanks for your reply. I'm unsure what direction to suggest here. 

I think what I expected to happen was that `onCancel(@CancelReason int cancelReason, @Nullable Throwable throwable)` would be called with a reason `CONDITIONS_NO_LONGER_MET`. Inside my job I would check for `isCancelled()` and return/finish the work. In this case you might also want to know what condition was not met as it might change how you handle it.

If I were to handle this currently I would throw my own exception inside `onRun()` and in the `shouldReRunOnThrowable(...)` I would check for the exception and schedule it myself later.

**Comment by yigit** [comment]
I see, makes sense though i think i would call this cancellation. We can probably make another callback when constraints are not met anymore and let you check it as a variable as well.

**Comment by yigit** [comment]
Btw, i'm very busy till IO but if you would like to try a PR, you can probably implement it in the `ConstraintsChange` message by traversing currently running jobs.

**Comment by liamheneghan** [comment]
I'll give it a go 👍
