### ISSUE TITLE
access to ApplicationComponent on JobQueue configuration

### ISSUE THREAD

**Issue by MahdiPishguy** [yigit/android-priority-jobqueue#346]
```
@Module(includes = ContextModule.class)
public class JobManagerModule {
    @Provides
    @GithubApplicationScope
    public JobManager jobManager(@ApplicationContext Context context) {

    component = DaggerApplicationComponent.builder()
            .githubApplicationComponent(Alachiq.getComponent())
            .build();

        Configuration.Builder builder = new Configuration.Builder(context)
                .injector(new DependencyInjector() {
                    @Override
                    public void inject(Job job) {
                       if (job instanceof Injectable) {
                          ((JobManagerInjectable) job).inject(component);
                       }
                    }
                });
        ...
        return new JobManager(builder.build());
    }
}
```

I get this error:

> Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536

how can i use `appComponent` in part of code: `((JobManagerInjectable) job).inject(appComponent);`

**Comment by yigit** [comment]
sorry your error has nothing to do w/ job manager. you are running your dex limit, please google.

**Comment by MahdiPishguy** [comment]
@yigit 

then is it this implementation correct sir?

**Comment by MahdiPishguy** [comment]
@yigit 
Thanks problem resolved
