### ISSUE TITLE
get UNKNOW for findjob

### ISSUE THREAD

**Issue by MahdiPishguy** [yigit/android-priority-jobqueue#354]
```
new Thread(new Runnable() {
    @Override
    public void run() {
        JobStatus salam = GetLatestRepositories.getJob(jobManager,getSessionId());
        Log.e("STATE ", "++++++++++++++++ ");
    }
}).start();
```
```
    public static JobStatus getJob(JobManager job, String tag) {
        return job.getJobStatus(tag);
    }
```

[I'm using this solution](https://github.com/yigit/android-priority-jobqueue/issues/32#issuecomment-125620443)

**Comment by yigit** [comment]
please provide proper bug reports w/ reproducible apps, and please don't use issues to resolve things related your custom implementations. Your bug report does not provide any actionable information.
