### ISSUE TITLE
How to Cancel a Job when there is no http request response

### ISSUE THREAD

**Issue by donpwilson** [yigit/android-priority-jobqueue#356]
I am using a Job to login to Google Drive. Recent changes at Google now require that such logins are via a browser (so that the user can see the address that is being accessed). This works well  in my app if the user accepts the prompts. However, I am trying to cover the circumstance when the user just closes the browser at this point. In this circumstance no exception is thrown and onResume() is (of course) triggered in my app.

I want to find a way of cancelling my Job in this circumstance. I am using EventBus and can successfully pass a message back to the Job from onResume(). I use threadMode = ThreadMode.ASYNC. I have then tried two possibilities:

1. Throw an exception in the Job to try to trigger onCancel(). This does not work because the callback is on the wrong thread. I tried to find the thread running the Job but Looper.myLooper().getThread() returned null so I was stuck.
2. Run onCancel() from the callback. This works correctly in terms of my app's processing but doesn't appear to "close" the Job, thereby clogging up the job queue. I tried to add super.onCancel() which I suspect would do the trick but this is not allowed.

I should perhaps add that I am using the CloudRail interface to access Google Drive and am in discussion with them to see if they could add an "abort" function. I could then run this from onResume() and the subsequent exception would trigger onCancel() in the Job correctly.

Any thoughts / solution?

**Comment by yigit** [comment]
I think you can TAG (`params.setTag`) all such jobs with `"REQUIRES_AUTH"`.
Then when you notice that auth failed, you can call cancel jobs API with that tag and JobManager will cancel them. If the job is already running, it won't be interrupted but if it fails, we'll cancel it.

**Comment by donpwilson** [comment]
I'm sorry not to respond earlier. I didn't notice that you had posted a response until you closed the issue.

Is "REQUIRES_AUTH" a special tag or is it specified by the app developer? If the latter, I'm already doing something like this. If not, is there any documentation anywhere? 

However, what I need is a way to interrupt / fail the job so that the thread is released. As far as I can see it is locked indefinitely. Could I be wrong about this?

**Comment by dreamcatcha** [comment]
Even though it is late, I will answer for anyone else looking.

"REQUIRES_AUTH" is just a string that you use as a tag for jobs that obviously are associated with authentication. You can cancel jobs via tags so to cancel all the jobs for auth you target the jobs with the tag "REQUIRES_AUTH". you could use any string "MyAuthJobs" etc, it doesn't matter

**Comment by donpwilson** [comment]
For further completeness, I have found a way of cancelling Jobs which are locked indefinitely waiting for an http response which does not come.

Within the Job I run a continuous loop to check for isCancelled():

```
    private void checkIfCancelled() {
        if (!isCancelled()) {
            if (!completed) {
                Threads.postDelayedOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        checkIfCancelled();
                    }
                }, 1000);
            }
        } else {
            onCancel(CancelReason.CANCELLED_WHILE_RUNNING, null);
        }
    }
```
In the above, "completed" is a boolean which is set to true when the Job is completed, either successfully or after cancellation. Also, in my utility class Threads:

```    
public static void postDelayedOnUiThread(Runnable task,int delay) {
        Handler handler = new Handler(Looper.getMainLooper());
        handler.postDelayed(task,delay);
    }
`

**Comment by maxime-kouemo** [comment]
How to detect if the job counsumers have no job at all?
