### ISSUE TITLE
When device restarted / switched off - queue is empty

### ISSUE THREAD

**Issue by jarojetu** [yigit/android-priority-jobqueue#360]
Hi question,

when we are in off-line without internet connectivity to our backend and have some jobs in queue and restart the device. All jobs are deleted from queue. **Is there any way how to persists all jobs in queue** even after device is restarted?

Regards Jan

**Comment by dsardari** [comment]
Are you setting the persist flag in the [Params](https://github.com/yigit/android-priority-jobqueue/blob/master/jobqueue/src/main/java/com/birbit/android/jobqueue/Params.java) when you create the [Job](https://github.com/yigit/android-priority-jobqueue/blob/master/jobqueue/src/main/java/com/birbit/android/jobqueue/Job.java#L57)?

**Comment by jarojetu** [comment]
Hi, thank this help and working now. 

Appreciate your answer, regards
