### ISSUE TITLE
.Persist throw this NotSerializableException when model class is using parcable

### ISSUE THREAD

**Issue by sandeep-agrawal** [yigit/android-priority-jobqueue#367]
I have a model class with parcable.

`public class Document implements Parcelable {

    @SerializedName("_id")
    @Expose
    private String id;
    @SerializedName("doc")
    @Expose
    private Doc doc = new Doc();
    @Expose
    private String status;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Doc getDoc() {
        return doc;
    }

    public void setDoc(Doc doc) {
        this.doc = doc;
    }

    public Document() {
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.id);
        dest.writeParcelable(this.doc, flags);
        dest.writeString(this.status);
    }

    protected Document(Parcel in) {
        this.id = in.readString();
        this.doc = in.readParcelable(Doc.class.getClassLoader());
        this.status = in.readString();
    }

    public static final Creator<Document> CREATOR = new Creator<Document>() {
        @Override
        public Document createFromParcel(Parcel source) {
            return new Document(source);
        }

        @Override
        public Document[] newArray(int size) {
            return new Document[size];
        }
    };`

public class Doc implements Parcelable {

    @SerializedName("modified_on")
    @Expose
    private String modifiedOn;
    @SerializedName("doc_type")
    @Expose
    private String docType;
    @SerializedName("desc")
    @Expose
    private String desc;
    @SerializedName("title")
    @Expose
    private String title;
    @SerializedName("image")
    @Expose
    private List<String> image = null;

    public String getModifiedOn() {
        return modifiedOn;
    }

    public void setModifiedOn(String modifiedOn) {
        this.modifiedOn = modifiedOn;
    }

    public String getDocType() {
        return docType;
    }

    public void setDocType(String docType) {
        this.docType = docType;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public List<String> getImage() {
        return image;
    }

    public void setImage(List<String> image) {
        this.image = image;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.modifiedOn);
        dest.writeString(this.docType);
        dest.writeString(this.desc);
        dest.writeString(this.title);
        dest.writeStringList(this.image);
    }

    public Doc() {
    }

    protected Doc(Parcel in) {
        this.modifiedOn = in.readString();
        this.docType = in.readString();
        this.desc = in.readString();
        this.title = in.readString();
        this.image = in.createStringArrayList();
    }

    public static final Parcelable.Creator<Doc> CREATOR = new Parcelable.Creator<Doc>() {
        @Override
        public Doc createFromParcel(Parcel source) {
            return new Doc(source);
        }

        @Override
        public Doc[] newArray(int size) {
            return new Doc[size];
        }
    };
}
`

My job class is something like this.

public class AddDocumentJob extends Job {
    public static final int PRIORITY = 1;
    private String kidId;
    private Document document;

    public AddDocumentJob(String kidId,Document document) {
        // This job requires network connectivity,
        // and should be persisted in case the application exits before job is completed.
        super(new Params(PRIORITY).requireNetwork().persist);
        this.kidId = kidId;
        this.document = document;
    }

    @Override
    public void onAdded() {
    }

    @Override
    public void onRun() throws Throwable {
        KidDocumentRequest kidDocumentRequest = new KidDocumentRequest();
        kidDocumentRequest.getDocuments().add(document);
        Call call = TeddyApis.getApi().saveKidDoc(kidId,kidDocumentRequest);
        Response<KidProfileDetailsResponse> response = call.execute();
        KidProfileDetailsResponse kidProfileDetailsResponse = response.body();
        if(kidProfileDetailsResponse.getStatus().equalsIgnoreCase("success")) {
            DataLayer.saveKidProfile(kidId,kidProfileDetailsResponse);
            sendKidUpdateBroadcast();
        } else {
            KidProfileDetailsResponse kidProfileDetailsResponse1 = DataLayer.getKidProfile(kidId,KidProfileDetailsResponse.class);
            kidProfileDetailsResponse1.getData().getDocuments().remove(document);
            DataLayer.saveKidProfile(kidId,kidProfileDetailsResponse1);
            sendKidUpdateBroadcast();
        }
        // Job logic goes here. In this example, the network call to post to Twitter is done here.
        // All work done here should be synchronous, a job is removed from the queue once
        // onRun() finishes.
        //webservice.postTweet(text);
    }

    public void sendKidUpdateBroadcast() {
        Intent intent = new Intent();
        intent.setAction(TeddyConstants.KID_DETAILS_UPDATE);
        LocalBroadcastManager.getInstance(getApplicationContext()).sendBroadcast(intent);
    }

    @Override
    protected RetryConstraint shouldReRunOnThrowable(Throwable throwable, int runCount,
                                                     int maxRunCount) {
        // An error occurred in onRun.
        // Return value determines whether this job should retry or cancel. You can further
        // specify a backoff strategy or change the job's priority. You can also apply the
        // delay to the whole group to preserve jobs' running order.
        return RetryConstraint.createExponentialBackoff(runCount, 1000);
    }

    @Override
    protected int getRetryLimit() {
        return 2;
    }
    @Override
    protected void onCancel(@CancelReason int cancelReason, @Nullable Throwable throwable) {
        // Job has exceeded retry attempts or shouldReRunOnThrowable() has decided to cancel.
    }
}
`

I am getting **NotSerializableException**.

**Comment by yigit** [comment]
JobManager uses java serialization by default so parcelable does not mean a thing (indeed, until L, there is not persistent parcelable). You need to either use java serialization or provide a custom serializer-deserializer (in the JobManager Config builder).
