### ISSUE TITLE
Memory Leak 

### ISSUE THREAD

**Issue by JessionYue** [yigit/android-priority-jobqueue#368]
hi  friend:
 How do you cut thread  execution when Activity is destroyed?  
 When Activity was destroyed, the thread named job-manager-callbacks

 also held a strong reference to Activiy.

my code is :(activity ondestrory)
  try{
            SKuaidiApplication.getInstance().getJobManager().cancelJobsInBackground(null, TagConstraint.ANY, sessionId);
            if(mJobManagerCallback!=null){
                SKuaidiApplication.getInstance().getJobManager().removeCallback(mJobManagerCallback);
                mJobManagerCallback=null;
                KLog.e("kb","removeJobCallBack");
            }
            new Thread(() -> {
                SKuaidiApplication.getInstance().getJobManager().clear();
                SKuaidiApplication.getInstance().getJobManager().destroy();
            }).start();
        }catch (Exception e){
            e.printStackTrace();
        }

**Comment by yigit** [comment]
you should not have a job that references back to the activity. even if you are cancelling it, it might be already running so job manager will wait until it fails or ends (see docs).
If you really need a back reference, make sure it is a weak reference.
