### ISSUE TITLE
Injected dependencies are serialized

### ISSUE THREAD

**Issue by colinrtwhite** [yigit/android-priority-jobqueue#371]
I'm seeing an issue in my crash reports where priority-jobqueue (v2.0.1) attempts to serialize my injected Retrofit reference. I'm injecting the Retrofit instance into my Job class using Dagger 2 and the following code:

    new Configuration.Builder(context)
				.injector(job -> {
					if (job instanceof PostVideoProgressJob) {
						CustomApplication.getComponent().inject((PostVideoProgressJob) job);
					}
				})

And my Job class:

    public class PostVideoProgressJob extends BaseJob {
    	private final Video video;

    	@Inject ServerInterface serverInterface;

    	public PostVideoProgressJob(@NonNull final Video video) {
    		super(new Params(PRIORITY_LOW)
    				.singleInstanceBy(String.valueOf(video.getId()))
    				.requireNetwork()
    				.persist());
    		this.video = video;
    	}

    	@Override
    	public void onRun() throws Throwable {
    		serverInterface.saveProgress(video.getId(), (int) TimeUnit.MILLISECONDS.toSeconds(video.getPlayTime())).blockingAwait();
    	}
    }

The exception occurs in the following case:
1. The Job runs instantly, but throws an exception.
2. It is then rescheduled and needs to be serialized to disk.
3. Any injected dependencies are serialized along with the Job instance.

[priority_job_queue_stack_trace.txt](https://github.com/yigit/android-priority-jobqueue/files/1033909/priority_job_queue_stack_trace.txt)

**Comment by colinrtwhite** [comment]
I can work around this issue by manually setting any injected dependencies to null, but maybe there's a better solution:

    public class PostVideoProgressJob extends BaseJob {
    	private final Video video;

    	@Inject ServerInterface serverInterface;

    	public PostVideoProgressJob(@NonNull final Video video) {
    		super(new Params(PRIORITY_LOW)
    				.singleInstanceBy(String.valueOf(video.getId()))
    				.requireNetwork()
    				.persist());
    		this.video = video;
    	}

    	@Override
    	public void onRun() throws Throwable {
    		try {
    			serverInterface.saveProgress(video.getId(), (int) TimeUnit.MILLISECONDS.toSeconds(video.getPlayTime())).blockingAwait();
    		} catch (Exception e) {
    			serverInterface = null;
    			throw e;
    		}
    	}
    }

**Comment by LuigiPapino** [comment]
declare transient the variable that can't be serialized

**Comment by colinrtwhite** [comment]
That solves it - thanks.
