### ISSUE TITLE
Handle operation result 

### ISSUE THREAD

**Issue by recepysl** [yigit/android-priority-jobqueue#386]
Hi,
Thats great work. Thanks again. The problem is the getting executing result. For example if my web service returns false, then i want to send it again.

**Comment by dsardari** [comment]
You could throw a custom throwable and in the [shouldReRunOnThrowable](https://github.com/yigit/android-priority-jobqueue/blob/master/jobqueue/src/main/java/com/birbit/android/jobqueue/Job.java#L210) either use the [exponential backoff RetryConstraint](https://github.com/yigit/android-priority-jobqueue/blob/master/jobqueue/src/main/java/com/birbit/android/jobqueue/RetryConstraint.java#L76) or return your own. It'll re-run your job until it reaches the retry limit.

**Comment by maxime-kouemo** [comment]
What I did to solve it was to throw and IOException in the onRun () when my webservice returned false. 

```
@Override
    public void onRun() throws Throwable {
	if(!isServerAccessible())
		throw new IOException("put this in the custom db to retry later");
	else
		doOnlineWork();
    }
```

```
@Override
    protected RetryConstraint shouldReRunOnThrowable(@NonNull Throwable throwable, int runCount, int maxRunCount) {
        if(throwable instanceof IOException || throwable instanceof IllegalArgumentException)
            return RetryConstraint.CANCEL;

        return null;
    }
```

 In onCancel, I save it in a local database using Room persistence (from Google). Later when some conditions are met, I try re sending them.

**Comment by jshvarts** [comment]
Or if you use RxJava in your remote service, you can utilize Rx operators such as  http://blog.danlew.net/2016/01/25/rxjavas-repeatwhen-and-retrywhen-explained/
