### ISSUE TITLE
Looking for a way to delay a task

### ISSUE THREAD

**Issue by hnguyenworkstation** [yigit/android-priority-jobqueue#387]
I would like to know if there is any way that we can delay a task for about 10 seconds from onAdded() to onRun(). I've been looking for a way to schedule a task to run after 10 seconds since it's added to disk but never seemed to work.

The scenario that I am trying to solve is that someone might try to hits "Like" button multiple times in a second, so I don't want to send multiple tasks calling the APIs so I want to add a task to disk if they hit "Like" and remove/cancel that task if they hit Like again. After 10 seconds, if the task is still in the disk, run it.

Thanks in advance and my apologies for any confusion.

**Comment by cristian-calugar** [comment]
Hi,

This is how we do this:

    private static final int JOB_DELAY = 10000;

    public SyncGroupsJob() {
        super(new Params(PRIORITY).persist().**delayInMs(JOB_DELAY)**);
    }

**Comment by hnguyenworkstation** [comment]
@cristian-calugar this is awesome! Thank you very much.
