### ISSUE TITLE
Retry network related tasks

### ISSUE THREAD

**Issue by vinaychandra** [yigit/android-priority-jobqueue#41]
If a set of tasks are marked requireNetwork  and have the same groupId for sequential execution, is there a way to delay the whole queue using either exponential backoff or something else so that the sequence of delivery is not effected?

**Comment by yigit** [comment]
Sorry, we don't have this support yet but it is feasible with the current backoff architecture. I'll keep this open for that implementation.

**Comment by zasunkx** [comment]
I agree, if you could back off an entire job group to preserve the execution order, that'd be great

**Comment by yigit** [comment]
released w/ 1.3.5
