### ISSUE TITLE
Unreachable code kotlin

### ISSUE THREAD

**Issue by nailbrother** [yigit/android-priority-jobqueue#424]
```
override fun onRun() {
TODO("not implemented") //To change body of created functions use File | Settings | File Templates.

val call = ApiService.sendAction("hi")
val reponse = call.execute()
if(reponse?.isSuccessful!!){
Log.w("SENT_JOB", "onRun: body = " + response.body().string())
}

}
```

Hi, I get unreachable code for this code !
I'm using kotlin with android studio 3.1 canary 5 and gradle plugin 3.0.1.
can anyone tell me why ? Thanks

**Comment by nailbrother** [comment]
It works with a `@Suppress("UNREACHABLE_CODE")` annotation ! but is there any other solutions ?

**Comment by guerjon** [comment]
Another Solution?

**Comment by kalpeshp0310** [comment]
You should remove
`TODO("not implemented") //To change body of created functions use File | Settings | File Templates.`

`TODO()` function in kotlin throws `NotImplementedError` making lines below this call unreachable. That's the reason behind IDE warning.

**Comment by jrcinco** [comment]
It is working when TODO("not implemented") is removed
