### ISSUE TITLE
I disagree with your deprecation because...

### ISSUE THREAD

**Issue by Zhuinden** [yigit/android-priority-jobqueue#465]
> For your persistent jobs, I recommend using WorkManager. For your non-persistent jobs, drink the kool aid and use Coroutines.

Non-persistent jobs that were enqueued until network is available are really useful.

I don't think you can do that with coroutines unless you implement a job queue over `Channel`, no?

**Comment by kingargyle** [comment]
@Zhuinden feel free to fork it and maintain your own version.

**Comment by Zhuinden** [comment]
Oh yeah! That's an option
