### ISSUE TITLE
How to stop/cancel the job in onAdded()?

### ISSUE THREAD

**Issue by yigit** [yigit/android-priority-jobqueue#5]
_From @m4hmoud on January 19, 2015 12:5_

Is there any way to cancel the current job in `onAdded()` and before even `onRun()` gets called?

_Copied from original issue: path/android-priority-jobqueue#89_

**Comment by yigit** [comment]
You can call `JobManager.cancelJobs`

**Comment by mendhak** [comment]
Could you add some sample code for tagging and cancelling? Maybe in the sample app or the wiki.  Sorry if you've added it already, I couldn't find any.

**Comment by yigit** [comment]
Added a page here: https://github.com/yigit/android-priority-jobqueue/wiki/Canceling-Jobs .
Lmk if it is good or not.

**Comment by mendhak** [comment]
Looks good, I added a bit, please remove if you feel it's wrong/useless.  Thanks a lot for your work.

**Comment by yigit** [comment]
What do you mean you've added, is there a pull request? (i don't see any).

**Comment by mendhak** [comment]
I edited your Wiki page, see revisions: https://github.com/yigit/android-priority-jobqueue/wiki/Canceling-Jobs/_history

**Comment by yigit** [comment]
Hmm, i didn't know anybody can change wiki :). Changes lgtm, thanks!

**Comment by dhinx** [comment]
First of all, thank you for your great work @yigit 

I got a problem when cancel job.

I want to cancel job when progress dialog is cancel. But, it doesn't work.

`
if (progressDialog == null) {
    progressDialog = new ProgressDialog(this);
    progressDialog.setMessage(getString(R.string.please_wait));
    progressDialog.setProgressPercentFormat(NumberFormat.getPercentInstance());
    progressDialog.setOnCancelListener(new DialogInterface.OnCancelListener() {
        @Override
        public void onCancel(DialogInterface dialog) {
            if (loginJob != null) {
                Log.e("progress dialog", "start cancel");
                cancelJobs(loginJob.getJobTag());
                MessageDialog.getInstance(LoginActivity.this)
                        .setTitle(R.string.title_confirmation)
                        .setMessage(R.string.ask_stop_process)
                        .setPositiveButton(R.string.label_yes, new DialogInterface.OnClickListener() {
                            @Override
                            public void onClick(DialogInterface dialog, int which) {
                                Log.e("message dialog", "yes");

                                if (loginJob != null) {
                                    cancelJobs(loginJob.getJobTag());
                                }

                                dialog.dismiss();
                            }
                        })
                        .setNegativeButton(R.string.label_no, new DialogInterface.OnClickListener() {
                            @Override
                            public void onClick(DialogInterface dialog, int which) {
                                doLoginJob();
                                dialog.dismiss();
                            }
                        })
                        .showDialog();
            }
        }
    });
}
`

The job didn't canceled too and open new activity in this code

`
@Override
public void onEventMainThread(Event.OnSuccessEvent event) {
    if (event.getProcessId() == ConstantJob.LOGIN) {
        Log.e("event", "sukses");

        if (loginJob != null && !loginJob.isCancelled()) {
            if (progressDialog != null && progressDialog.isShowing()) {
                progressDialog.dismiss();
            }
            loginJob = null;

            if (Preferences.getInstance().getPreferences().getBoolean(Preferences.HAS_INITIATE, false)) {
                startActivity(new Intent(this, DashboardActivity.class));
                finish();
            } else {
                startActivityForResult(new Intent(this, BuildingWizardActivity.class), Constants.WIZARD_BUILDING_ACTIVITY);
            }
        }
    }
}
`

Please, help me. Thank you.

Here's my full code.

**Activity Class**

`public class LoginActivity extends WizardBaseActivity implements OnEventMainThread<Void, Void, String, String> {

    static String TAG = "LoginActivity";

    @Bind(R.id.field_username) EditText usernameField;
    @Bind(R.id.field_password) EditText passwordField;
    @Bind(R.id.image_logo) ImageView logoImage;

    private ProgressDialog progressDialog;
    private ImageLoader imageLoader = ImageLoader.getInstance();

    private LoginJob loginJob;

    @Override
    protected void onStart() {
        super.onStart();
        registerEvent();
    }

    @Override
    protected int layout() {
        return R.layout.activity_login;
    }

    @Override
    public void onViewCreated() {
        hideNavigationBar();

//        startService(new Intent(this, SyncDataService.class));
        if (Preferences.getCurrentEmployeeId() > 0) {
            startActivity(new Intent(this, DashboardActivity.class));
            finish();
        }

        if (Preferences.getBuildingInfo() != null) {
            Building building = Preferences.getBuildingInfo();
            if (building.getLogoUrl() != null) {
                imageLoader.displayImage("file://" + Preferences.getBuildingLogoLocal(), logoImage);
            }
        }
    }

    @SuppressWarnings("unused")
    @OnClick(R.id.button_login)
    public void doLogin() {
        if (usernameField.getText().length() == 0) {
            MessageDialog.getInstance(this).setMessage(R.string.message_empty_username).showDialog();
        } else if (passwordField.getText().length() == 0) {
            MessageDialog.getInstance(this).setMessage(R.string.message_empty_password).showDialog();
        } else {
            Employee employee = Employee.findSingle(Employee.class, "username = ?", usernameField.getText().toString());
            if (employee == null) {
                doLoginJob();
            } else {
                String password = Util.generatePassword(passwordField.getText().toString());
                if (password.equals(employee.getPassword())) {
                    Preferences.setCurrentEmployeeId(employee.getId());
                    startActivity(new Intent(this, DashboardActivity.class));
                    finish();
                } else {
                    Toast.makeText(this, getString(R.string.message_wrong_username_password), Toast.LENGTH_LONG).show();
                }
            }
        }
    }

    @SuppressWarnings("unused")
    @OnCheckedChanged(R.id.checkbox_show_password)
    public void onCheckedChange(boolean isChecked) {
        if (isChecked) {
            passwordField.setInputType(InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD);
        } else {
            passwordField.setInputType(InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_VARIATION_PASSWORD);
        }

        passwordField.setSelection(passwordField.getText().length());
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (resultCode == Activity.RESULT_OK) {
            if (requestCode == Constants.WIZARD_BUILDING_ACTIVITY) {
                startActivityForResult(new Intent(this, PrinterWizardActivity.class), Constants.WIZARD_PRINTER_ACTIVITY);
            } else if (requestCode == Constants.WIZARD_PRINTER_ACTIVITY) {
                startActivityForResult(new Intent(this, DownloadWizardActivity.class), Constants.WIZARD_DOWNLOAD_ACTIVITY);
            } else if (requestCode == Constants.WIZARD_DOWNLOAD_ACTIVITY) {
                if (Preferences.getBuildingInfo() != null) {
                    Building building = Preferences.getBuildingInfo();
                    if (building.getLogoUrl() != null) {
                        imageLoader.displayImage("file://" + Preferences.getBuildingLogoLocal(), logoImage);
                    }
                }
            }
        }
    }

    @Override
    public void onEventMainThread(Event.OnExecuteEvent event) {
        if (event.getProcessId() == ConstantJob.LOGIN) {
            Log.e("event", "execute");
            if (progressDialog == null) {
                progressDialog = new ProgressDialog(this);
                progressDialog.setMessage(getString(R.string.please_wait));
                progressDialog.setProgressPercentFormat(NumberFormat.getPercentInstance());
                progressDialog.setOnCancelListener(new DialogInterface.OnCancelListener() {
                    @Override
                    public void onCancel(DialogInterface dialog) {
                        if (loginJob != null) {
                            Log.e("progress dialog", "start cancel");
                            cancelJobs(loginJob.getJobTag());
                            MessageDialog.getInstance(LoginActivity.this)
                                    .setTitle(R.string.title_confirmation)
                                    .setMessage(R.string.ask_stop_process)
                                    .setPositiveButton(R.string.label_yes, new DialogInterface.OnClickListener() {
                                        @Override
                                        public void onClick(DialogInterface dialog, int which) {
                                            Log.e("message dialog", "yes");

                                            if (loginJob != null) {
                                                cancelJobs(loginJob.getJobTag());
                                            }

                                            dialog.dismiss();
                                        }
                                    })
                                    .setNegativeButton(R.string.label_no, new DialogInterface.OnClickListener() {
                                        @Override
                                        public void onClick(DialogInterface dialog, int which) {
                                            doLoginJob();
                                            dialog.dismiss();
                                        }
                                    })
                                    .showDialog();
                        }
                    }
                });
            }

            if (progressDialog != null && !progressDialog.isShowing()) {
                progressDialog.show();
            }
        }
    }

    @Override
    public void onEventMainThread(Event.OnSuccessEvent event) {
        if (event.getProcessId() == ConstantJob.LOGIN) {
            Log.e("event", "sukses");

            if (loginJob != null && !loginJob.isCancelled()) {
                if (progressDialog != null && progressDialog.isShowing()) {
                    progressDialog.dismiss();
                }
                loginJob = null;

                if (Preferences.getInstance().getPreferences().getBoolean(Preferences.HAS_INITIATE, false)) {
                    startActivity(new Intent(this, DashboardActivity.class));
                    finish();
                } else {
                    startActivityForResult(new Intent(this, BuildingWizardActivity.class), Constants.WIZARD_BUILDING_ACTIVITY);
                }
            }
        }
    }

    @Override
    public void onEventMainThread(Event.OnCancelEvent<String> event) {
        if (event.getProcessId() == ConstantJob.LOGIN) {
            Log.e("event", "cancel");
            if (progressDialog != null && progressDialog.isShowing()) {
                progressDialog.dismiss();
            }
            loginJob = null;

            Toast.makeText(this, event.getResult(), Toast.LENGTH_LONG).show();
        }
    }

    @Override
    public void onEventMainThread(Event.OnFailedEvent<String> event) {
        if (event.getProcessId() == ConstantJob.LOGIN) {
            Log.e("event", "failed");
            Toast.makeText(this, event.getResult(), Toast.LENGTH_LONG).show();

            if (progressDialog != null && progressDialog.isShowing()) {
                progressDialog.dismiss();
            }
            loginJob = null;
        }
    }

    protected void doLoginJob() {
        if (loginJob == null) {
            loginJob = new LoginJob(
                    Priority.HIGH,
                    usernameField.getText().toString(),
                    passwordField.getText().toString()
            );
        }
        addJobs(loginJob);
    }
}
`
**Job Class**
`
public class LoginJob extends DefaultJob {

    private String username;
    private String password;

    public LoginJob(int priority, String username, String password) {
        super(priority, true);
        this.username = username;
        this.password = password;
    }

    @SuppressWarnings("unchecked")
    @Override
    public void onAdded() {
        postEvent(new Event.OnExecuteEvent<Void>(ConstantJob.LOGIN, null));
        Log.e("job", "added " + getJobTag());
    }

    @SuppressWarnings("unchecked")
    @Override
    public void onRun() throws Throwable {
        try {
            Log.e("job", "run " + getJobTag());

//            PosquityApplication.getInstance().cancelJob(getJobTag());
            Thread.sleep(TimeUnit.SECONDS.toMillis(5));
                postEvent(new Event.OnSuccessEvent<Void>(ConstantJob.LOGIN, null));
        } catch (Exception e) {
            e.printStackTrace();
            postEvent(new Event.OnFailedEvent<>(ConstantJob.LOGIN, getContext().getString(R.string.message_failed_task)));
            Log.e("job", "exception " + getJobTag());
        }
        Log.e("job", "finish run " + getJobTag());
    }

    @SuppressWarnings("unchecked")
    @Override
    protected void onCancel() {
        postEvent(new Event.OnCancelEvent<String>(ConstantJob.LOGIN, getContext().getString(R.string.message_wrong_username_password)));
        Log.e("job", "cancel " + getJobTag());
    }
}
`
