### ISSUE TITLE
Error when adding job, and onRun never called.

### ISSUE THREAD

**Issue by kenneth488** [yigit/android-priority-jobqueue#50]
Hey yigit

No matter what I do, I get this warning when adding a job to the manager.

E/AppLog: customLogger:error while serializing object %s java.io.NotSerializableException:

The code is simple:

JobManager jobManager=new JobManager(context,new Configuration.Builder(context).customLogger(new CustomLogger()
        {
            @Override
            public boolean isDebugEnabled()
            {
                return true;
            }

            @Override
            public void d(final String text,final Object... args)
            {
                //Log.d("AppLog","customLogger:"+text+" "+args);
            }

            @Override
            public void e(final Throwable t,final String text,final Object... args)
            {
                Log.e("AppLog","customLogger:"+text+" "+t+" "+args);
            }

            @Override
            public void e(final String text,final Object... args)
            {
                Log.e("AppLog","customLogger:"+text+" "+args);
            }
        }).build());

        for(int i = 0; i < 5; i++) {
            jobManager.addJobInBackground(new Job(new Params(1).requireNetwork().persist()) {
                @Override
                public void onAdded() {
                }

                @Override
                public void onRun() throws Throwable {
                    //Log.d("onRun - ","RUN");
                }

                @Override
                protected void onCancel() {

                }
            });
        }

The context is set to: private transient Context context;

What am I doing wrong here.

Best regards,

Kenneth

**Comment by yigit** [comment]
you are trying to create an anonymous class but ask job manager to persist it.
You need to create a class (that is not anonymous) and then you can add it as persistable.

The error is clear such that you cannot serialize that class (thus cannot mark it persistent).
