### ISSUE TITLE
Retrofit errorHandler

### ISSUE THREAD

**Issue by LinkOut** [yigit/android-priority-jobqueue#53]
onRun() im running my server call using retrofit, i got 2 callbacks success and error, how can i do (onError) to throw an exception that shouldReRunOnThrowable handles? 

Thanks

**Comment by mseshachalam** [comment]
throw an exception from the onError or do not handle the exception, both will cause the shouldReRunOnThrowable to run. you can handle the exception and throw your own Throwable instance.

**Comment by LinkOut** [comment]
What i ve done is throw new Exception onError but this do not run shouldReRunOnThrowable method.

**Comment by yigit** [comment]
I'm assuming you are using async retrofit API. No reason to do it inside the job, just run it synchronously as Jobs are designed to work sync. It will throw the exception when you call it sync or if you are using retrofit 2, you can check `response.isSuccess` and throw it there.

Sample code:
    
    final Call<FeedResponse> feed = mApiService.feed(timestamp);
    Response<FeedResponse> response = feed.execute();
    Response<FeedResponse> response = feed.execute();
    if (response.isSuccess()) {
        // handle response
    } else {
        // throw the exception
    }

**Comment by LinkOut** [comment]
Hello, thanks for you'r answer. Actually what i ve done is not using callbacks, so i did the request sync. The exception is thrown by retrofit.
