### ISSUE TITLE
Table job_holder_tags not updating

### ISSUE THREAD

**Issue by panayiotis-andreou** [yigit/android-priority-jobqueue#56]
Hi @yigit, thanks for this excellent library 

I have noticed that tags from job_holder_tags table are not deleted when a job is deleted from the job_holder table, as a result tags in job_holder_tags table reference on a job that does not exists in job_holder table. 

Thanks in advance

**Comment by yigit** [comment]
Hmm, we are expecting persistent jobs to have a limited number of tags that are frequently re-used and I think this tag table is very unlikely to grow large. What is your use case?

JobManager can deal with deleting unused tags but that'll require additional querying and I don't see much benefit in doing this. 
Alternatively, we may provide a configuration parameter to delete and vacuum database before JobManager starts. The downside is that it will be doing unnecessary work the time you need resources the most (app initialization).

Can you explain more details on your use case and why this table may grow? We can also consider adding an API to do the cleanup and vacuuming.

**Comment by panayiotis-andreou** [comment]
Thank you for your response. 

My use case is when the user creates a record on the databases i schedule a job to push this record on the server. This job is persistent and will have a unique tag based on a static value and the id of the new record.  

Also i have a synchronisation service that runs every X time which gets the status from the server and compare them with the local status (numbers of records, version of each record, deleted records, records that should be downloaded on the device). if a record not exists on the server i check if it is on the job manager's queue with the findJobByTag and reschedule it if is needed.

I am using this library for all of these jobs and each job has it's own unique tag which helps me to keep phone and server synchronised. 

Thanks in advance

**Comment by yigit** [comment]
Seems legit since you'll be creating many of these tags. On the other hand, for your implementation, it is better to do the check in Job's onRun method so that if its item is already synced, it will just silently end. This way, it will be self contained and still won't have any race conditions.

**Comment by panayiotis-andreou** [comment]
ok thank you very much for advice

**Comment by yigit** [comment]
this is fixed in v2.
