### ISSUE TITLE
Doze awareness in NetworkUtilImpl should take into consideration PowerManager.isIgnoringBatteryOptimizations

### ISSUE THREAD

**Issue by vchatterji** [yigit/android-priority-jobqueue#57]
Refering to the implementation of NetworkUtilImpl:
https://github.com/yigit/android-priority-jobqueue/blob/master/jobqueue/src/main/java/com/path/android/jobqueue/network/NetworkUtilImpl.java

The current implementation does not take into account if app has been whitelisted by user to access network in the background. The following code should be more appropriate:
```java
     /**
     * Returns true if the device is in Doze/Idle mode. Should be called before checking the network connection because
     * the ConnectionManager may report the device is connected when it isn't during Idle mode.
     */
    @TargetApi(23)
    private static boolean isDozing(Context context) {
        if (VERSION.SDK_INT >= 23) {
            PowerManager powerManager = (PowerManager) context.getSystemService(Context.POWER_SERVICE);
            final String myPackageName = context.getPackageName();
            if(!powerManager.isIgnoringBatteryOptimizations(myPackageName)) {
                   return powerManager.isDeviceIdleMode();
            } else {
                   return false;
            }
        } else {
            return false;
        }
    }
```

A current workaround to this issue is to provide implementation of NetworkUtil interface while configuring JobManager.

**Comment by yigit** [comment]
Seems legit. Please send a pull request and I'll merge it.
Also, I'd rather it return in single statement for clarity:

`return !powerManager.isIgnoringBatteryOptimizations(myPackageName) && powerManager.isDeviceIdleMode()`
