### ISSUE TITLE
Github specific: forked repositories are not currently searchable.

### ISSUE THREAD

**Issue by sandys** [yigit/android-priority-jobqueue#58]
I'm having trouble searching your repo for any code, references, etc. because Github throws a message saying "Sorry, forked repositories are not currently searchable. You could try searching the parent repository. "

Could you figure out how to fix this please ?

**Comment by yigit** [comment]
I'm not sure if this is fixable on my end but I'll look for a solution :/. I wonder what happens if we shut down the original project.

**Comment by kingargyle** [comment]
See https://help.github.com/articles/searching-repositories/ for information on how to include forked repositories in search results.  By default github doesn't search forked repositories.

**Comment by sandys** [comment]
heres a short update - http://stackoverflow.com/a/33666719/112050

>When a fork has less stars than its parent, it is not indexed at all for code search. So it won't show up even when you use fork:true. The fork:true search filter is used to show results for forks that have been indexed for search.

>In the example of the TeamTwisted/external_chromium_org fork, that code is searchable because it has more stars than its parent repo. However the PEZ/Sketch-Plugin-Testing-Repo fork does not, so it won't be searchable at all with any filter.

**Comment by yigit** [comment]
:/. I'm not sure what to do here. I'll try to find somebody from Github to see if there is another way. It is unlikely to have as many stars in this project any time soon.

**Comment by sandys** [comment]
I think its time for jobqueue to break away from Path !

May I suggest renaming it with a cool name - Square always has good names.
I would have called it "Rope" or "Lace" ;)

**Comment by yigit** [comment]
I've contacted support and they detached the project. It is searchable now :).

And in V2, i'm probably changing the package name since I rewrote most of it, I'm breaking some bad APIs (with better replacements) and I might as well break the package :).

**Comment by yigit** [comment]
and I may as well re-name it but not sure about Rope or Lace :/.

**Comment by sandys** [comment]
awesome!  really excited to see what you come up with.

**Comment by sandys** [comment]
@yigit - can you please pick a name quickly ? most of us are deferring upgrade until you set the name. we would rather not refactor twice !

**Comment by mseshachalam** [comment]
@yigit name suggestion

**Haberdashery**

```
noun: haberdashery; plural noun: haberdasheries
    1.
    British
    small items used in sewing, such as buttons, zips, and thread.
    2.
    North American
    men's clothing and other items sold by a haberdasher.
```
