### ISSUE TITLE
dagger2 integration

### ISSUE THREAD

**Issue by sandys** [yigit/android-priority-jobqueue#59]
hi,
any chance you could update the examples with Dagger2 ? there's been a lot of a questions on stackoverflow,etc. about this.. but nobody knows the correct way.

**Comment by yigit** [comment]
I actually just hit this case while writing the architecture demo for the dev summit. I should update the sample app here but until then, here is my solution:

``` java
    @Provides
    @Singleton
    public JobManager jobManager() {
        Configuration config = new Configuration.Builder(mApp)
                 ....
                .injector(new DependencyInjector() {
                    @Override
                    public void inject(Job job) {
                        if (job instanceof BaseJob) {
                            ((BaseJob) job).inject(mApp.getAppComponent());
                        }
                    }
                })
                .build();
        return new JobManager(mApp, config);
    }
```


So unfortunately I end up adding another base class to introduce inject method that receives a component.
Then a sample Job's inject method looks like:

``` java
    @Override
    public void inject(AppComponent appComponent) {
        super.inject(appComponent);
        appComponent.inject(this);
    }
```

**Comment by sandys** [comment]
Hi
Thank you so much for replying.

I'm actually trying to use a third party library (Pusher.com) to fire an
websocket call inside a job.
The problem is that I'm forced to use it as transient...but I'm not sure
how to inject the Singleton pusher instance into the job.

Regards
Sandeep

**Comment by sandys** [comment]
your solution works great!!
I'm closing this issue.

**Comment by giacomodeglinnocenti** [comment]
whats kind of object is the 'mApp' variable?
