### ISSUE TITLE
How to start persisted jobs?

### ISSUE THREAD

**Issue by markini** [yigit/android-priority-jobqueue#60]
Hello.

What I want to do:
1. Restart persisted jobs on application launch.
2. Restart persisted jobs on connectivity change (to connected) when the app is sleeping.

How do I do this:
As of now, the only way I see it, is to add a new job, then the old persisted jobs are running with the new one. 

I expected (without reading the code) that `myJobManager.start()` would start the old persisted jobs but that doesn't seem to be the case.

Is there a way to restart persisted jobs without adding a new job?

**Comment by yigit** [comment]
JobManager takes care of restarting the job if it has not run successfully already or cancelled (and other conditions are matched like network requirement).
Just make sure you create the JobManager when your application starts and rest will be taken care.
If this is not the behavior you are seeing, please provide a sample app where I can reproduce the error or at least assign a logger in the configuration and share the logs.

**Comment by markini** [comment]
It took me a while to figure it out. 
My test application worked like it should be and now I know what to do to reproduce it.
See this little test app: https://github.com/markini/JobTestProject
The interesting classes are `TestJobApplication` (here is the configuration of the JobManager) and `TestJob`. 

When you click on the FAB, the `TestJob` starts which has a 13 second sleep period. When you kill the app while sleeping and restart it, the persisted job won't start again. 

The thing is, it all works like expected when I remove the `NetworkUtil`. 
For testing purpose I added this `NetworkUtil`:

```java
.networkUtil(new NetworkUtil() {
  @Override
  public boolean isConnected(Context context) {
    return true;
  }
})
```

Is there something wrong with a `NetworkUtil` like this?

**Comment by yigit** [comment]
Hmm, the default network utility also notifies when network comes back.
(see: https://github.com/yigit/android-priority-jobqueue/wiki/Job-Manager-Configuration) / NetworkEventProvider . 

But seems like yours always return true so should not need a notification. 
I'll debug the app and see whats going on.

**Comment by markini** [comment]
Thanks you already pointed me in the right direction. 
I now just extend the already very good `NetworkUtilImpl` and overwrite the `isConnected` method. 
With this it works like a charm. 
I didn't dig deep enough into to code to figure out why a bland `NetworkUtils`implementation disturbs the expected outcome though...
