### ISSUE TITLE
Behavior of addJob() when JobManager is stopped

### ISSUE THREAD

**Issue by bbbln** [yigit/android-priority-jobqueue#63]
Hi. Thank you for sharing this great project. I just have a simple question I cannot answer from the documentation or the wiki:
What is the behavior of addJob() (or any of the other adding methods) when the job queue is stopped. Should I ensure that no job is added while the queue is stopped and store the jobs myself or is it fine to use addJob() and the jobs will run as soon as the queue is started again?

Thanks, Bjoern.

**Comment by yigit** [comment]
Yes, they'll be added as usual and will be run when the JQ restarts.
