### ISSUE TITLE
serializing complex classes inside jobs

### ISSUE THREAD

**Issue by sandys** [yigit/android-priority-jobqueue#65]
hi,
we have a complex class (with lots of strings, hashmaps,etc.) that we want to persist with the job. I dont want to override your entire serializer, but I just want to make this class pay nice with you.

what is a good way to do that ?

regards
sandeep

**Comment by yigit** [comment]
You don't need anything special if your data is already serializable (or mark everything that cannot be serialized as transient).
JobQueue uses Java serialization by default.
https://docs.oracle.com/javase/tutorial/jndi/objects/serial.html

Btw if these objects are really really big (e.g. 200KB), consider saving them into a flat file and save that file's location in your job. JobQueue saves jobs into an sqlite database and big objects may create issues with SQLiteCursorWindow.

**Comment by sandys** [comment]
closing bug, because was able to serialize using java serializers
