### ISSUE TITLE
JobManager and Android 5.0 JobScheduler

### ISSUE THREAD

**Issue by yigit** [yigit/android-priority-jobqueue#7]
_From @mseshachalam on January 12, 2015 6:47_

Does the JobScheduler work as same as JobManager ? Will there be any new changes that take advantage of JobScheduler in this library ?

_Copied from original issue: path/android-priority-jobqueue#86_

**Comment by yigit** [comment]
I didn't get a chance to play w/ job scheduler there is probably something we can take advantage of.

**Comment by AndroidDeveloperLB** [comment]
Please do add support to use this API. It has some nice features, and the main advantage is that it is global, and checks when it's a good time to batch operate jobs of multiple apps.

**Comment by yigit** [comment]
v2 supports this: https://github.com/yigit/android-priority-jobqueue/wiki/Integration-with-JobScheduler-and-GcmNetworkManager
