### ISSUE TITLE
Persist job's properties must can be serialization

### ISSUE THREAD

**Issue by nb7123** [yigit/android-priority-jobqueue#71]
error while serializing object XXXJob
java.io.NotSerializableException:XXX

**Comment by nb7123** [comment]
call method Job.persist() to set params persist

**Comment by yigit** [comment]
Exception is clear, your job is NOT persistable.
JobManager uses Java serialization by default so you should either make your job class java serializable or provide a custom serializer.
https://github.com/yigit/android-priority-jobqueue/wiki/Job-Manager-Configuration

**Comment by nb7123** [comment]
Thank you very much!
