### ISSUE TITLE
Battery draining issue

### ISSUE THREAD

**Issue by ravenet** [yigit/android-priority-jobqueue#80]
Dear yigit,
You have done great framework. However, I am using this library one of my apps related with transportation. I created many jobs, and it is working fine. After quite some times I noticed that there is a serious issue taht the job always keep alive one consumer, so that my app power consumption is high. Moreover, in order to double confirm this issue, I remove the this lib, and change to asyncTask. It is give me surprise it is not taking  so much battery.

So, How to improve the battery life with this library. or do you have roadmap to fix this problem in the future.
Thanks

**Comment by yigit** [comment]
You can set minConsumerCount to 0 to avoid having a keep alive thread but that should not be the issue.
Is this something you can reproduce? If you can reproduce the issue and enable logs, it may have important information. Maybe, JobManager goes into some busy loop for whatever reason but cannot say much w/o information. Also, JobManager should help with your battery usage not hurt :/

**Comment by ravenet** [comment]
Hi Yigit,

Thank you for your response, and I will try to create a test case or similar things to send you later. Because it is very hard to produce unless I need to run this for a long time.

However, If we set consumercount 0, what would be performance impact ?
Thanks

**Comment by ravenet** [comment]
Hi,
I reproduced the issue, and here is log, and screenshot of CPU usage where my app is doing nothing, it is simple activity where it is finished, but CPU every a few seconds CPU goes 0.11%

01-08 10:09:09.710 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:09:09.710 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:09:09.710 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:09:09.710 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:09:09.710 21379-21417/SAMPLE D/JOBS: Thread-3921: load factor check. true = (0 < 1)|| (0 * 3 < 0 + 0). consumer thread: true
01-08 10:09:09.710 21379-21417/SAMPLE D/JOBS: didn't allow me to die, re-running Thread-3921
01-08 10:09:09.710 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:09:09.710 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:09:09.710 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:09:09.710 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:09:09.710 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:09:09.710 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:09:09.710 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:09:09.710 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:09:09.710 21379-21417/SAMPLE D/JOBS: re-running consumer Thread-3921
01-08 10:11:09.710 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:11:09.710 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:11:09.710 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:11:09.710 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:11:09.710 21379-21417/SAMPLE D/JOBS: Thread-3921: load factor check. true = (0 < 1)|| (0 * 3 < 0 + 0). consumer thread: true
01-08 10:11:09.710 21379-21417/SAMPLE D/JOBS: didn't allow me to die, re-running Thread-3921
01-08 10:11:09.710 21379-21417/SAMPLE D/JOBS: re-running consumer Thread-3921
01-08 10:11:09.710 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:11:09.710 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:11:09.710 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:11:09.710 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:11:09.715 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:11:09.715 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:11:09.715 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:11:09.715 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:13:09.715 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:13:09.715 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:13:09.715 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:13:09.715 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:13:09.715 21379-21417/SAMPLE D/JOBS: Thread-3921: load factor check. true = (0 < 1)|| (0 * 3 < 0 + 0). consumer thread: true
01-08 10:13:09.715 21379-21417/SAMPLE D/JOBS: didn't allow me to die, re-running Thread-3921
01-08 10:13:09.715 21379-21417/SAMPLE D/JOBS: re-running consumer Thread-3921
01-08 10:13:09.715 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:13:09.715 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:13:09.715 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:13:09.715 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:13:09.715 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:13:09.720 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:13:09.720 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:13:09.720 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:15:09.715 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:15:09.715 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:15:09.715 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:15:09.715 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:15:09.720 21379-21417/SAMPLE D/JOBS: Thread-3921: load factor check. true = (0 < 1)|| (0 * 3 < 0 + 0). consumer thread: true
01-08 10:15:09.720 21379-21417/SAMPLE D/JOBS: didn't allow me to die, re-running Thread-3921
01-08 10:15:09.720 21379-21417/SAMPLE D/JOBS: re-running consumer Thread-3921
01-08 10:15:09.720 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:15:09.720 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:15:09.720 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:15:09.720 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:15:09.720 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:15:09.720 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:15:09.720 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:15:09.720 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:17:06.210 21379-21379/SAMPLE I/Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
01-08 10:17:09.725 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:17:09.725 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:17:09.725 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:17:09.725 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:17:09.725 21379-21417/SAMPLE D/JOBS: Thread-3921: load factor check. true = (0 < 1)|| (0 * 3 < 0 + 0). consumer thread: true
01-08 10:17:09.725 21379-21417/SAMPLE D/JOBS: didn't allow me to die, re-running Thread-3921
01-08 10:17:09.725 21379-21417/SAMPLE D/JOBS: re-running consumer Thread-3921
01-08 10:17:09.725 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:17:09.725 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:17:09.725 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:17:09.725 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:17:09.725 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:17:09.725 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:17:09.730 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:17:09.730 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:17:54.115 21379-21385/SAMPLE I/dalvikvm: TRACE STARTED: '[DDMS]' 8192KB
01-08 10:17:54.130 21379-21385/SAMPLE D/dalvikvm: JIT code cache reset in 0 ms (176712 bytes 1/0)
01-08 10:17:54.130 21379-21385/SAMPLE D/dalvikvm: +++ active profiler count now 1
01-08 10:18:15.510 21379-21385/SAMPLE D/dalvikvm: +++ active profiler count now 0
01-08 10:18:15.760 21379-21385/SAMPLE I/dalvikvm: TRACE STOPPED: writing 4099 records
01-08 10:19:09.725 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:19:09.725 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:19:09.725 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:19:09.725 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:19:09.725 21379-21417/SAMPLE D/JOBS: Thread-3921: load factor check. true = (0 < 1)|| (0 * 3 < 0 + 0). consumer thread: true
01-08 10:19:09.725 21379-21417/SAMPLE D/JOBS: didn't allow me to die, re-running Thread-3921
01-08 10:19:09.725 21379-21417/SAMPLE D/JOBS: re-running consumer Thread-3921
01-08 10:19:09.725 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:19:09.725 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:19:09.725 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:19:09.725 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:19:09.725 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:19:09.725 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:19:09.730 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:19:09.730 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:21:09.725 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:21:09.725 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:21:09.725 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:21:09.725 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:21:09.730 21379-21417/SAMPLE D/JOBS: Thread-3921: load factor check. true = (0 < 1)|| (0 * 3 < 0 + 0). consumer thread: true
01-08 10:21:09.730 21379-21417/SAMPLE D/JOBS: didn't allow me to die, re-running Thread-3921
01-08 10:21:09.730 21379-21417/SAMPLE D/JOBS: re-running consumer Thread-3921
01-08 10:21:09.730 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:21:09.730 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:21:09.730 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:21:09.730 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:21:09.730 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:21:09.730 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:21:09.730 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:21:09.730 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:21:20.840 21379-21385/SAMPLE I/dalvikvm: TRACE STARTED: '[DDMS]' 8192KB
01-08 10:21:20.850 21379-21385/SAMPLE D/dalvikvm: +++ active profiler count now 1
01-08 10:22:06.855 21379-21385/SAMPLE D/dalvikvm: +++ active profiler count now 0
01-08 10:22:07.100 21379-21385/SAMPLE I/dalvikvm: TRACE STOPPED: writing 10670 records
01-08 10:23:09.730 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:23:09.730 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:23:09.730 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:23:09.730 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:23:09.730 21379-21417/SAMPLE D/JOBS: Thread-3921: load factor check. true = (0 < 1)|| (0 * 3 < 0 + 0). consumer thread: true
01-08 10:23:09.730 21379-21417/SAMPLE D/JOBS: didn't allow me to die, re-running Thread-3921
01-08 10:23:09.730 21379-21417/SAMPLE D/JOBS: re-running consumer Thread-3921
01-08 10:23:09.730 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:23:09.730 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:23:09.735 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:23:09.735 21379-21417/SAMPLE D/JOBS: persistent result null
01-08 10:23:09.735 21379-21417/SAMPLE D/JOBS: looking for next job
01-08 10:23:09.735 21379-21417/SAMPLE D/JOBS: running groups 
01-08 10:23:09.735 21379-21417/SAMPLE D/JOBS: non persistent result null
01-08 10:23:09.735 21379-21417/SAMPLE D/JOBS: persistent result null


![cpu](https://cloud.githubusercontent.com/assets/6859970/12188694/b3d72b78-b5f2-11e5-99ab-25589285f4a6.png)

I hope it helps.
Thanks

**Comment by yigit** [comment]
Yea this looks bad, the job is expected to be sleeping when there are no jobs until the lock is invoked. Setting min consumer to 0 should solve it but I don't like that idea. 
If you are setting a custom network util that does not provide network events, this might happen but even in that case, it should not be so frequent.
Can you share your job manager configuration? I can also upload a version with more logging to the snapshot repository to get more information. Also, is this some app I can reach? You can email me a debug enabled APK and that should be enough for me to attach and debug the job queue.

**Comment by ravenet** [comment]
Dear Yigit,
Once again thank you for your time, and

1. I don't have custom network util class
2. The configuration is exactly same like your twitter sample,
  private void configureJobManager() {
        Configuration configuration = new Configuration.Builder(this)
                .customLogger(new CustomLogger() {
                    private static final String TAG = "JOBS";

                    @Override
                    public boolean isDebugEnabled() {
                        return true;
                    }

                    @Override
                    public void d(String text, Object... args) {
                        Log.d(TAG, String.format(text, args));
                    }

                    @Override
                    public void e(Throwable t, String text, Object... args) {
                        Log.e(TAG, String.format(text, args), t);
                    }

                    @Override
                    public void e(String text, Object... args) {
                        Log.e(TAG, String.format(text, args));
                    }
                })
                .minConsumerCount(1)//always keep at least one consumer alive
                .maxConsumerCount(3)//up to 3 consumers at a time
                .loadFactor(3)//3 jobs per consumer
                .consumerKeepAlive(120)//wait 2 minute
                .build();
        jobManager = new JobManager(this, configuration);
    }

3. Unfortunately, I can not publish APK due to some security reasons. However, I can create a simple sample to reproduce the issue, and then it seems it is common issue when you are set network does not required( my guess). I will try to post sample application here.

Thanks

**Comment by yigit** [comment]
Can you change the logger to be like:

 Log.d(TAG, String.format(text, args), new Exception());
 Log.e(TAG, String.format(text, args), new Exception());

This is going to log the call stack to better understand why it is querying multiple times. Btw, one case I'm thinking is if network status changes frequently, some CPU usage might be triggered although it should not trigger "check for jobs".
I can also send you a version that can log each time consumers are notified, or you can build it yourself if you are comfortable doing it.

Thanks a lot, this is important and I would like to fix it very much :).

**Comment by ravenet** [comment]
Hi Yigit,
Thank you for your time, and I will change the log as you mentioned, and then I will place a network status change receiver to monitor claims too.

Thanks

**Comment by jongha** [comment]
+1

**Comment by rhlff** [comment]
+1

**Comment by rhlff** [comment]
Hi Yigit,

I experienced the same issue with version 1.3.5, it works fine with previous versions. Therefore I keep v1.3.4 until it is fixed.

It keeps logging again and again:
```
D/JOBS: looking for next job
D/JOBS: running groups
D/JOBS: non persistent result null
```

You can checkout the app I'm working on: https://github.com/openHPI/android-app

Thanks

**Comment by russelldavies** [comment]
I've also been experiencing this issue, the job manager goes into a spin and device CPU goes to 20%. I tried v1.3.4 and got this error: `error while serializing object MyJob` which wasn't being displayed on v1.3.5. Correcting the `MyJob` class seems to have resolved this problem.

**Comment by chchgb** [comment]
＋1

**Comment by yigit** [comment]
@chchgb  Are you observing this issue with v1 or v2?

**Comment by russelldavies** [comment]
I haven't observed this issue since using v2.

**Comment by pzhangleo** [comment]
I have observed this issue when connect with wifi using v2.
This is log:
06-22 18:03:00.092 11378-11483/com.being.fame.debug V/JobLogger: [ConnectivityManager][queue_CONSTRAINT_CHANGE_2] post message com.birbit.android.jobqueue.messaging.message.ConstraintChangeMessage@5ba434d
06-22 18:03:00.092 11378-11486/com.being.fame.debug V/JobLogger: [job-manager][priority_mq] looking for next message at time 1466589780110551152
06-22 18:03:00.102 11378-11486/com.being.fame.debug V/JobLogger: [job-manager]flushing messages at time 1466589780110551152
06-22 18:03:00.172 11378-11486/com.being.fame.debug V/JobLogger: [job-manager][priority_mq] next delayed job null
06-22 18:03:00.172 11378-11486/com.being.fame.debug V/JobLogger: [job-manager][queue_CONSTRAINT_CHANGE_2] remove message com.birbit.android.jobqueue.messaging.message.ConstraintChangeMessage@5ba434d
06-22 18:03:00.172 11378-11486/com.being.fame.debug V/JobLogger: [job-manager][priority_mq] consuming message of type CONSTRAINT_CHANGE
06-22 18:03:00.212 11378-11486/com.being.fame.debug V/JobLogger: [job-manager]considering adding a new consumer. Should poke all waiting? true isRunning? true waiting workers? 0
06-22 18:03:00.442 11378-11384/com.being.fame.debug W/art: Suspending all threads took: 9.314ms
06-22 18:03:00.482 11378-11486/com.being.fame.debug V/JobLogger: [job-manager]check above load factor: totalCons:0 minCons:0 maxConsCount: 5, loadFactor 3 remainingJobs: 0 runningsHolders: 0. isAbove:false
06-22 18:03:00.482 11378-11486/com.being.fame.debug V/JobLogger: [job-manager]nothing has been poked. are we above load factor? false
06-22 18:03:00.482 11378-11486/com.being.fame.debug V/JobLogger: [job-manager][priority_mq] looking for next message at time 1466589780498493860
06-22 18:03:00.482 11378-11486/com.being.fame.debug V/JobLogger: [job-manager]flushing messages at time 1466589780498493860
06-22 18:03:00.482 11378-11486/com.being.fame.debug V/JobLogger: [job-manager][priority_mq] next delayed job null
06-22 18:03:00.482 11378-11486/com.being.fame.debug V/JobLogger: [job-manager][queue_CONSTRAINT_CHANGE_2] remove message null
06-22 18:03:00.492 11378-11486/com.being.fame.debug V/JobLogger: [job-manager]joq idle. running:? true
06-22 18:03:00.682 11378-11465/com.being.fame.debug E/com.bugtags.lib.agent: TransactionStateUtil: Attempting to convert network exception java.net.ConnectException to error code.
06-22 18:03:00.882 11378-11486/com.being.fame.debug V/JobLogger: [job-manager]Job queue idle. next job at: null
06-22 18:03:00.882 11378-11486/com.being.fame.debug V/JobLogger: [job-manager][priority_mq] did on idle post a message? false
06-22 18:03:08.462 11378-11384/com.being.fame.debug W/art: Suspending all threads took: 8.862ms
06-22 18:03:08.462 11378-11483/com.being.fame.debug V/JobLogger: [ConnectivityManager][queue_CONSTRAINT_CHANGE_2] post message com.birbit.android.jobqueue.messaging.message.ConstraintChangeMessage@5ba434d
06-22 18:03:08.462 11378-11486/com.being.fame.debug V/JobLogger: [job-manager][priority_mq] looking for next message at time 1466589788477464430
06-22 18:03:08.462 11378-11486/com.being.fame.debug V/JobLogger: [job-manager]flushing messages at time 1466589788477464430
06-22 18:03:08.462 11378-11486/com.being.fame.debug V/JobLogger: [job-manager][priority_mq] next delayed job null
06-22 18:03:08.462 11378-11486/com.being.fame.debug V/JobLogger: [job-manager][queue_CONSTRAINT_CHANGE_2] remove message com.birbit.android.jobqueue.messaging.message.ConstraintChangeMessage@5ba434d
06-22 18:03:08.462 11378-11486/com.being.fame.debug V/JobLogger: [job-manager][priority_mq] consuming message of type CONSTRAINT_CHANGE
06-22 18:03:08.472 11378-11486/com.being.fame.debug V/JobLogger: [job-manager]considering adding a new consumer. Should poke all waiting? true isRunning? true waiting workers? 0
06-22 18:03:08.502 11378-11486/com.being.fame.debug V/JobLogger: [job-manager]check above load factor: totalCons:0 minCons:0 maxConsCount: 5, loadFactor 3 remainingJobs: 0 runningsHolders: 0. isAbove:false
06-22 18:03:08.502 11378-11486/com.being.fame.debug V/JobLogger: [job-manager]nothing has been poked. are we above load factor? false
06-22 18:03:08.512 11378-11486/com.being.fame.debug V/JobLogger: [job-manager][priority_mq] looking for next message at time 1466589788521437503
06-22 18:03:08.512 11378-11486/com.being.fame.debug V/JobLogger: [job-manager]flushing messages at time 1466589788521437503
06-22 18:03:08.512 11378-11486/com.being.fame.debug V/JobLogger: [job-manager][priority_mq] next delayed job null
06-22 18:03:08.512 11378-11486/com.being.fame.debug V/JobLogger: [job-manager][queue_CONSTRAINT_CHANGE_2] remove message null
06-22 18:03:08.512 11378-11486/com.being.fame.debug V/JobLogger: [job-manager]joq idle. running:? true
06-22 18:03:08.562 11378-11486/com.being.fame.debug V/JobLogger: [job-manager]Job queue idle. next job at: null
06-22 18:03:08.562 11378-11486/com.being.fame.debug V/JobLogger: [job-manager][priority_mq] did on idle post a message? false
06-22 18:03:15.602 11378-11483/com.being.fame.debug V/JobLogger: [ConnectivityManager][queue_CONSTRAINT_CHANGE_2] post message com.birbit.android.jobqueue.messaging.message.ConstraintChangeMessage@5ba434d
06-22 18:03:15.622 11378-11486/com.being.fame.debug V/JobLogger: [job-manager][priority_mq] looking for next message at time 1466589795632723802
06-22 18:03:15.632 11378-11486/com.being.fame.debug V/JobLogger: [job-manager]flushing messages at time 1466589795632723802

**Comment by yigit** [comment]
v2's infinite message passing issue has been fixed and i've just released v2. please test with it.
