### ISSUE TITLE
Job Queue was based on Command Design Pattern ?

### ISSUE THREAD

**Issue by KhoaSuperman** [yigit/android-priority-jobqueue#81]
Hi contributor, thank you so much for awesome work you did :)

I'm learning design pattern and currently I'm reading Command Pattern
http://www.javacodegeeks.com/2015/09/command-design-pattern.html

So I guest Job queue was base on it but much more improvements :)

Is this right? I'm curious about that :)

**Comment by yigit** [comment]
Hmm, to be honest, this is the first time I hear about that :). 
Before working on mobile, I used to work on the server side and there are message queues that are used to do similar tasks (send an email, register tracking events etc). JobManager was our solution at Path to have a similar architecture and help scale the application.

**Comment by KhoaSuperman** [comment]
Oh I understand. Thank for your sharing :)
