### ISSUE TITLE
After calling stop on JobManager it does not start

### ISSUE THREAD

**Issue by dkadrikj** [yigit/android-priority-jobqueue#84]
Hi,

After I call stop on the JobManager instance then it does not start automatically, even if I call start. The "boolean running" field is false.

**Comment by yigit** [comment]
calling start sets it to true directly so not sure how it stays as false. Are you sure you are not creating multiple instances by mistake?

https://github.com/yigit/android-priority-jobqueue/blob/master/jobqueue/src/main/java/com/path/android/jobqueue/JobManager.java#L119
