### ISSUE TITLE
Online / offline not working properly

### ISSUE THREAD

**Issue by ramden** [yigit/android-priority-jobqueue#87]
Hello,
I am using this library with following goals in mind:

* Be offline
* Create some jobs and persist them
* Become online
* Jobs get executed

----

My problems are following: 
* All jobs I create seems not to be persisted. I use following:

`super(new Params(PRIORITY).persist().requireNetwork().addTags("SOMETAG");`

Does requireNetwork() mean the jobs are not being created if no network (offline) ? 

---

* Does the library detect online/ offline? I tried this:

com.path.android.jobqueue.config.Configuration configuration = new com.path.android.jobqueue.config.Configuration.Builder(this)
                .networkUtil(new NetworkUtil() {
                    @Override
                    public boolean isConnected(Context context) {
                        return isNetworkAvailable();
                    }
                })
                .minConsumerCount(1)//always keep at least one consumer alive
                .maxConsumerCount(3)//up to 3 consumers at a time
                .loadFactor(3)//3 jobs per consumer
                .consumerKeepAlive(120)//wait 2 minute
                .build();

---

* Retry strategy: How to make jobs run infinite?

**Comment by yigit** [comment]
Attach a logger and check logs, if your persistent jobs are not being persistent, they are probably not persistable.

`requireNetwork` means run the job only when there is a network connection.

Seems like your are implementing custom NetworkUtility (why not the default one?) See the network util section for details: https://github.com/yigit/android-priority-jobqueue/wiki/Job-Manager-Configuration

re: Retry strategy: How to make jobs run infinite?
Give them a large retry count and always return retry from `shoulReRun` (see main page for an example).

**Comment by ramden** [comment]
That mostly worked. Just one more thing... Where to set the retry count?

**Comment by ramden** [comment]
Got it. In the job you override getRetryLimit() 

`@Override
    protected int getRetryLimit() {
        return 1000000;
    }`
