### ISSUE TITLE
Replace a foreground service

### ISSUE THREAD

**Issue by MFlisar** [yigit/android-priority-jobqueue#90]
Is it possible to replace a foreground service with a job?

Sometimes, I want something to not stop at all until it's finished and I would use a foreground service, can this be replaced with a job?

As far as I can see, the only thing that comes near to that is a persistant job but this job may be stopped if I exit the app (although it restarts when I start the app again).

The texts in the readme somehow sound like replacing a service is possible as well...

If I see that correctly, it's not possible, all I can do is running a non persistant job in a service (or start a service when starting the job) and stop the service, when the job has finished, is that correct? But then I could just do the job's action directly in the service...

**Comment by yigit** [comment]
Jobs are designed to finish so running an infinite job is not really a supported use case. If you only worry about having your app running, you can create a dummy foreground service which will keep your app alive and run individual tasks using JobManager. But again, if you want something that runs forever, jobs are not the correct solution. In the README, we reference to solutions where people create a thread pool in a service.

**Comment by MFlisar** [comment]
In the jobs `onRun` method I create a notification and update it, so I see when the job is stopped because the process is killed => the notification is not removed and does not update itself anymore...

I don't need the job to run forever, but to finish only...

Using a persistant job makes the job restart when I open the app again, a normal job may just be stopped in the middle...

I know how to solve that with a service, I was just curious if this really is necessary (for a one time job, that should just finish, not run forever)

**Comment by shakil807g** [comment]
@yigit  i have the same use case in my app . where user can upload  multiple files to a server 
and i want to  keep uploading  media  and showing notification like we can achieve with a foreground service , even when the app is close by user

**Comment by yigit** [comment]
You can easily do this w/ v2.
Create your foreground service when jobs are created. Add a callback to the JobManager to get notified when jobs are done and when are all complete, you can finish the foreground service. (also update the notification as things progress).

Tests use this to assert jobs are done. You can use it as an example point to start:

https://github.com/yigit/android-priority-jobqueue/blob/c203793f8d27ba84c5ba5a147fa4212859463830/jobqueue/src/test/java/com/birbit/android/jobqueue/test/jobmanager/JobManagerTestBase.java#L274

**Comment by shakil807g** [comment]
Thank @yigit  your answer is super helpful. But one last thing can i start
foreground service from  onAdded method of job or before job creation  and
how can i update progress in notification of foreground service. Beacuase
uploading in done on jobs

**Comment by yigit** [comment]
JobManager.Callback is invoked after each job is done so you can get the information there.
You should de-couple the creation of the service from the job though. Especially for persistent jobs since the job instance that runs will be different than the job instance that receives onAdded call.

**Comment by shakil807g** [comment]
Thanks again for your quick responses. but it is also possible for a job to keep notify about data being uploaded on server  ( like keep sending progress to activity or foreground service  to show in notification) ? not just sending event when job is finish

**Comment by yigit** [comment]
yea of course, if you have an eventbus or using local broadcast you can do that. Jobs have access to the application context while running. (see: http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/Job.html#getApplicationContext--)
