### ISSUE TITLE
Snapshot

### ISSUE THREAD

**Issue by AlokBansal8** [yigit/android-priority-jobqueue#96]
How to get the snapshot version. Please add the details, possibly in readme file.

**Comment by yigit** [comment]
`compile 'com.birbit:android-priority-jobqueue:2.0-SNAPSHOT'`

**Comment by yigit** [comment]
you also need to add snapshot repository to your build.gradle file.

     maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots/'
    }

see:
https://github.com/yigit/android-priority-jobqueue/blob/master/examples/twitter/TwitterClient/build.gradle
