### ISSUE TITLE
v2 branch: AsyncAddCallback doesn't pass an ID

### ISSUE THREAD

**Issue by 3flex** [yigit/android-priority-jobqueue#99]
I know v2 is WIP but I'm trying to follow along for an app that I'm working on that would benefit from some of those features.

I'm hoping `onAdded()` in `AsyncAddCallback` can be modified to start passing the new UUID-based ID. Thanks!

**Comment by yigit** [comment]
You don't need that. The new UUID is assigned when you create the job and job has a getId method.

**Comment by 3flex** [comment]
Ah, I see now... sorry for the noise :(
